### ISSUE TITLE
IDE hangs when minimized and file is updated outside

### ISSUE THREAD

**Issue by phantasm** [jrsoftware/issrc#112]
1. Open some ISS file in Inno Setup GUI
2. Minimize Inno Setup window to taskbar
3. Edit this file with some other text editor, then save it
4. Click on Inno Setup taskbar button
5. You will see "Do you want to reload" dialog
6. Regardless of the choice, Inno Setup window will not emerge from taskbar any further. You will need to close it and restart.

![3fe3f-clip-32kb](https://cloud.githubusercontent.com/assets/369127/3817090/a0a09b88-1cd4-11e4-95dd-895da66be81f.jpg)

**Comment by maldoinc** [comment]
The first reference to this issue mistakenly uses an old branch from another PR. 

I believe PR #164 resolves this issue. Please tell me if it also works for you.
