### ISSUE TITLE
{commondocs} issues

### ISSUE THREAD

**Issue by yfede** [jrsoftware/issrc#144]
When installing in 64 bit mode, it seems that the {commondocs} constant gets resolved without disabling WOW64, because I am getting the wrong path (I am getting the location that is setup for the 32-bit subsystem rather than the actual 64-bit one).

I haven't tested the other {common\*} or either {user\*} constants, but I suspect the issue may be there too, and hasn't been detected until now because on the majority of systems the 32-bit and 64-bit paths for those folders are the same

**Comment by martijnlaan** [comment]
Can you provide more info? Has your commondocs dir been changed to a subdir of the System32 dir or something?

**Comment by DeeHants** [comment]
I wasn't aware there could be architecture specific versions of those folders.

**Comment by yfede** [comment]
Well, neither was I, but I found out the hard way when a customer described the issue he was facing after having installed one of the product I work on, whose installer for the 64-bit version is built with InnoSetup and installs some files in the {commondocs} folder.

First of all, the customer is running a 64-bit installation of Windows 7 and, long before running the mentioned installer, he managed to relocate the Public Documents folder from the default path "C:\Users\Public\Documents" to a folder of his choice, namely "D:\Public\Documents", with the intent of moving the public documents away from his small SSD (C:) and onto his regular (and bigger) hard disk (D:).

I have asked how did he manage to do so, but he was unable to explain.
However, I have been able to reproduce the same situation following the procedure explained here: http://superuser.com/questions/16883/move-the-public-folders-on-windows-7

Under those circumstances, I ran the same installer and, as he reported, the files installed to {commondocs} weren't installed to "D:\Public\Documents" as they were supposed to, but they ended up in their default place instead: "C:\Users\Public\Documents".

On the other hand, the installed product, which retrieves the path of the public documents folder using the CSIDL constants and functions of the Windows API, correctly sees the customized path on D: for the public documents and searches them there, finding none.

At that point, I considered what difference could arise from the fact that my application is a 64-bit application, while the installer generated by InnoSetup is always a 32-bit application.
That, in conjunction with the fact that all those special folder paths are stored in the registry, made me take a look at 'regedit' and a hint was there:

the path "D:\Public\Documents" is stored in the following registry key:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common Documents

while the path "C:\Users\Public\Documents" is stored in the following registry key:
HKEY_LOCAL_MACHINE\SOFTWARE\\__Wow6432Node__\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders

Thus, it seems that a native 64-bit application, when obtaining the public documents folder, may correctly receive the "D:\Public\Documents" that is stored in the registry. On the other hand, a 32-bit application on the same system, because of the intervention of the WOW node, may obtain the "C:\Users\Public\Documents" value instead.

It goes without saying that, as a developer myself, I am not ok at all with the fact that, via the relocation procedure linked above, a functioning Windows installation can return two different paths when asked for the public documents folder, depending on whether the requesting application is 32-bit or 64-bit. However, since we don't have the power to enforce the same path to be returned at all times, I think the best that can be done is to have consistent results: installers in 64-bit mode should return the 64-bit path because that's what installed 64-bit applications will see, and the same holds for regular 32-bit installers for 32-bit applications

Sorry for the long post, the subject was not easily explained in shorter but clearer terms.
Best regards

**Comment by yfede** [comment]
Any news about this?

**Comment by martijnlaan** [comment]
Sounds like a broken system to me where your customer moved their {commondocs} in a bad way. I would need to see some official MSDN documentation confirming that your customer followed an official procedure before considering this issue further.
