### ISSUE TITLE
Enable the RmForceShutdown option for Restart Manager

### ISSUE THREAD

**Issue by Elusive138** [jrsoftware/issrc#145]
[Currently](https://github.com/jrsoftware/issrc/blob/fcd29a583579acfe092e0c0bbf5503872d3957ec/Projects/Install.pas#L2775), InnoSetup's use of Restart Manager calls [`RmShutdown`](http://msdn.microsoft.com/en-us/library/windows/desktop/aa373667.aspx) without specifying any options.

Unfortunately, it seems that the [shutdown process](http://msdn.microsoft.com/en-us/library/windows/desktop/aa373651.aspx) will not work on a GUI application that does not process messages (e.g. does not have a window). <sup>This is my guess at the reason for the failure: I haven't confirmed the reason yet, but the solution works in any case.</sup> This will cause `RmShutdown` to return a `ERROR_FAIL_SHUTDOWN`, and InnoSetup gets stuck in the "unable to automatically close all applications" loop.

The application I'm currently trying to install and update with InnoSetup includes a browser component based on Chromium, which starts several render GUI processes that do not have a main window attached, and therefore will not respond to the shutdown messages. In my scenario, Restart Manager will *never* work as it is currently implemented.

Passing `RmForceShutdown` (`0x1`) as the second argument for `RmShutdown` solves this by forcibly terminating all applications after a timeout, including those that do not respond to window messages. This is of course somewhat risky, as it effectively kills processes that do not cooperate. On the other hand, processes that do not process `WM_ENDSESSION` will be forcibly terminated in the same fashion on logoff, so it's probably no more dangerous than a system restart. <sup>Possible edge case: a worker process belonging to some other process, e.g. a service - in a normal logoff sequence the parent process would close the workers properly. I don't think the Restart Manager can detect this scenario, and would just end up terminating the worker...</sup>

I believe InnoSetup should implement one of the following:

* Always pass `RmForceShutdown`. After all, the user has already been prompted with the list of processes (unless in silent mode...).

* Provide either a setup script option or command-line option to enable force-shutdown. This would leave it up to the setup-creator to decide whether it's a safe action.

* Add a "force close" to the abort-retry-ignore dialog, or just replace the retry with a "force close". This would give the user the choice, at the expense of annoying them more.

**Comment by DeeHants** [comment]
You may want to check this pull request 137 that has some more commentary about this:
https://github.com/jrsoftware/issrc/pull/137

**Comment by Elusive138** [comment]
Ah, I was only searching open issues. Thanks for the link.

So it seems that the first option is ruled out as being too dangerous. I still believe I have a valid use-case here, where the application in question fails to be shut down due to the lack of a message pump, rather than replying false to the `WM_QUERYENDSESSION` (e.g. prompting the user to save, the example from the PR). No amount of retries without the force option will *ever* work.

Unfortunately, the Restart Manager API doesn't seem to provide any option to treat the two differently - seems either the blunt force-shutdown is necessary, or a custom script to go and kill all processes manually.

**Comment by martijnlaan** [comment]
Closing for the reasons stated in my last message in #137

**Comment by Elusive138** [comment]
Of the reasons you provided in that message, the only one that really applies is the reboot-fallback (which is undesirable where it can be avoided).

I still suggest, e.g., adding a `ForceCloseApplications` option so it is configurable at compile-time. That hopefully should not incur extra translation work, and without the option `CloseApplications` becomes completely useless in cases like this - as explained above, retries will *never* work.

This issue actually seems to be a duplicate of #125, with the addition of a concrete example of when Restart Manager will fail (GUI-mode programs without a message pump).

It is of course possible to manually script the termination of every process in `PrepareToInstall`, though it is unlikely to be as elegant as the current `CloseApplications` UI.

**Comment by joaomoreno** [comment]
@Elusive138 did you ever get Inno to restart your Chromium based application?

**Comment by Elusive138** [comment]
@joaomoreno I can't recall. I can check what we ended up doing on Monday, if I remember.

I *think* we ended up scripting the force close, but we might have just ignored the issue and instructed the user to manually close all instances.

**Comment by joaomoreno** [comment]
The problem with manually closing is that if you are running with `/silent` the application doesn't get launched automatically. Without that parameter, there is the "Run application" checkbox.

**Comment by Elusive138** [comment]
Nup, never got around to scripting the force close. So we're left with the default action if the file is locked.

As for not getting launched automatically, you could probably just remove the `skipifsilent` flag on the run step.

**Comment by joaomoreno** [comment]
Yeah figured it out eventually. :+1: Thanks for the update!

**Comment by pmalhaire** [comment]
I faced a similar issue 
I need explorer.exe to be closed to update a shell extension dll
on WIN 8 & WIN 10 restart manager fails indefinetely

**Comment by martijnlaan** [comment]
Ok, I still think this is a bad idea since you might cause lost work for the user (like the Notepad example of #137) but I will look into adding an option for this.

**Comment by pmalhaire** [comment]
@martijnlaan I agree it's not the best thing to do, and that windows restart manager should take better care of this case. But as for now it's the best proposal.

**Comment by ciarancourtney** [comment]
Hi @martijnlaan sorry for asking, but when do you think 5.5.7 might be released? I'm particularly interested in the FORCECLOSEAPPLICATIONS directive
