### ISSUE TITLE
Could not copy "Setup.e32" to "appdir\Setup.e32.tmp"

### ISSUE THREAD

**Issue by promatik** [jrsoftware/issrc#146]
I've made a script that worked for a long time. I recently changed my machine and now I'm having this issue:
```Could not copy "C:\...\Inno Setup 5\Setup.e32" to "C:\...\appdir\Setup.e32.tmp"```

The file and output folder exists, I tried to run it with admin privilege by the cmd and by the app (script editor), with no success.

**Comment by DeeHants** [comment]
Have you tried disabling your antivirus?

**Comment by promatik** [comment]
Yes, I'm using Microsoft Windows Essentials (Windows Defender?) I disabled it and also UAC.

**Comment by martijnlaan** [comment]
Closing, I don't think this is a proper place for such a question.
