### ISSUE TITLE
Support class definition

### ISSUE THREAD

**Issue by SergejKern** [jrsoftware/issrc#147]
Hello there,

could you please support definition of classes in InnoSetup Code section, that would support better code structure in large projects.

Thanking in advance,
Sergej

**Comment by DeeHants** [comment]
This is a (lack of) feature in the [ROPS/script engine](http://www.remobjects.com/ps.aspx) in use.

**Comment by SergejKern** [comment]
Thanks for an answer! I'll post my issue there
