### ISSUE TITLE
Bug? Result seems to be static

### ISSUE THREAD

**Issue by SergejKern** [jrsoftware/issrc#150]
Dear contributors,

today I found something very strange, using 5.5.5(u) on Win7x64.

Given simple sample record:
```
type SomeType = record
  sName: String;
  a_Arr: array of SomeOtherType;
end;
```

Given "factory" function to create a record:
```
function CreateSomeType(par_sName: String): SomeType;
begin
  Result.sName := par_sName;
end;

// somewhere in Code:
stMyFirstObject := CreateSomeType('test');
```
When I call ```CreateSomeType``` first time everything is fine: ```Result``` is empty as expected.
After that I fill array ```a_Arr``` with stuff.
Then I call ```CreateSomeType``` to create another object. ```Result``` is strangely not empty. It contains all the data which were written to ```Result``` and to (not global) variable ```stMyFirstObject```, which is actually not expected at all. So I need to rewrite function ```CreateSomeType``` to look like following.

```
function CreateSomeType(par_sName: String): SomeType;
begin
  Result.sName := par_sName;
  // Reset array because Result seems to be static!!!! \0_o/
  SetArrayLength(Result.a_Arr, 0);
end;
```

That works for me, but please don't tell me that this is normal pascal behavior.

Best regards,
Sergej

**Comment by martijnlaan** [comment]
As said before, post these kind of issues at https://github.com/remobjects/pascalscript/issues
