### ISSUE TITLE
Current Release broken for ISPP defines begining with O

### ISSUE THREAD

**Issue by vincentparrett** [jrsoftware/issrc#152]
I just updated my build machine to 555 and it's not outputting a setup  - "Skipping creating setup files, output is disabled" 

The cause is the new /do option, when I have a ispp define OutputRoot - which is passed on the command line 

"/dOutputRoot=S:\......."

It looks like it's fixed in the repo (option changed to O+|- ) So how do we get a new release without building it ourself?

**Comment by KngStr** [comment]
Well. 5.5.5 already fixed this bug.
I just tested, it works fine.

**Comment by vincentparrett** [comment]
Hmmm.. I just downloaded isetup-5.5.5-unicode.exe and this is what I get


Usage:  iscc [options] scriptfile.iss
or to read from standard input:  iscc [options] -
Options:  Emulate a #define or #pragma directive:
            /d<name>[=<value>]   #define public <name> <value>
            /$<letter>(+|-)      #pragma option -<letter>(+|-)
            /p<letter>(+|-)      #pragma parseroption -<letter>(+|-)
            /i<paths>            #pragma include <paths>
            /{#<string>          #pragma inlinestart <string>
            /}<string>           #pragma inlineend <string>
            /v<number>           #pragma verboselevel <number>
          Disable output (overrides Output):
            /do
          Enable output (overrides Output):
            /eo
          Output files to specified path (overrides OutputDir):
            /o<path>
          Override OutputBaseFilename with the specified filename:
            /f<filename>
          Set a SignTool with the specified name and command:
            /s<name>=<command>
          Quiet compile (print error messages only):
            /q
          Enable quiet compile while still displaying progress:
            /qp

**Comment by vincentparrett** [comment]
There's no version info in the exe's so impossible to tell what version is actually installed.

**Comment by KngStr** [comment]
Sorry. I made a mistake! You can copy one from older version.

**Comment by DeeHants** [comment]
@KngStr : 5.5.5 actually introduced the bug.

**Comment by vincentparrett** [comment]
Please re-open, the current release 5.5.5 still has this bug!

**Comment by DeeHants** [comment]
It's been closed as it's [already been fixed](https://github.com/jrsoftware/issrc/commit/997f738253ca130e4b61698b20293e3e2bd7b135) and is [waiting on the next release](http://jrsoftware.github.io/issrc/whatsnew.htm).

**Comment by vincentparrett** [comment]
Is there a timeframe for this new release?

**Comment by DeeHants** [comment]
Not that I've heard, but believe that the Windows 10 changes are waiting until the final release of Windows 10.
