### ISSUE TITLE
Multibytes string in script becomes "??" in 5.5.5 unicode

### ISSUE THREAD

**Issue by brianpow** [jrsoftware/issrc#153]
If a multibytes string is directly assigned in script, it becomes "?"
If a multibytes string is expanded from [CustomMessages], it works.
The iss file is in UTF-8
Why?

#Screenshot#
http://postimg.org/image/v90rpujhd/

#Test Script#
```[Setup]
#define AppVersion "XXX"
#define AppName "Test"
AppName={#AppName} Trial Version
AppVerName={#AppName} {#AppVersion}
VersionInfoProductName={#AppName}
DefaultDirName={pf}\{#AppName}
DefaultGroupName={#AppName}
OutputBaseFilename=..\..\{#AppName} v{#AppVersion}
[Custommessages]
Test=АБ 
[Code]
var
  DBPage: TInputQueryWizardPage;
Procedure InitializeWizard;
begin
  DBPage := CreateInputQueryPage(wpWelcome,'Unicode Test', '','');
  DBPage.Add('АБ', False);
  DBPage.Add(CustomMessage('Test'), False);
end;
```

**Comment by DeeHants** [comment]
From the Unicode Inno Setup page in the help file:
> The new RemObjects PascalScript version used by the Unicode compiler supports Unicode, but not for its input source. This means it does use Unicode string types as said, but any literal Unicode characters in the script will be converted to ANSI. This doesn't mean you can't display Unicode strings: you can for example instead use encoded Unicode characters to build Unicode strings (like `S := #$0100 + #$0101 + 'Aa';`), or load the string from a file using `LoadStringsFromFile`, or use a `{cm:...}` constant.

This is not a bug in Inno Setup.
