### ISSUE TITLE
Using invalid file name characters in the "OutputBaseFilename" directive causes an installation error

### ISSUE THREAD

**Issue by brianpow** [jrsoftware/issrc#154]
If I use custom message in  "OutputBaseFilename" under [setup] section, it compiles successfully but causes error during installation. The reason behind may be ":" cannot be used as filename and {cm:file} is not expanded during installation
![iserror](https://cloud.githubusercontent.com/assets/647087/6796467/a00b03ba-d22e-11e4-8fda-17875feb14f6.PNG)

```
[Setup]
AppName=Test
AppVersion=1
DefaultDirName={pf}\Test
DefaultGroupName=Test
OutputBaseFilename={cm:file}
[custommessage]
file=My Program
```

**Comment by DeeHants** [comment]
`OutputBaseFilename` does not accept runtime `{constants}` which can only be used where the documentation explicitly says so.
If you want dynamically generated values, look at ISPP.

As for the error, maybe Inno should check if the directive is valid as a filename and abort the compile if not.
(Leaving open for Martijn's comment on the character check)

**Comment by jogo-** [comment]
Why not adding/using such following utility functions for the compiler to check all fixed file/folder names in Inno Setup scripts ?
http://docwiki.embarcadero.com/Libraries/XE8/fr/System.IOUtils.TPath.HasValidFileNameChars
http://docwiki.embarcadero.com/Libraries/XE8/fr/System.IOUtils.TPath.HasValidPathChars
http://docwiki.embarcadero.com/Libraries/XE8/fr/System.IOUtils.TPath.IsValidFileNameChar
http://docwiki.embarcadero.com/Libraries/XE8/fr/System.IOUtils.TPath.IsValidPathChar
