### ISSUE TITLE
ishelp: Missing help on 'ssPreInstall' TSetupStep constant

### ISSUE THREAD

**Issue by jogo-** [jrsoftware/issrc#156]
The following definition gives an undocumented 'ssPreInstall' constant:
`TSetupStep = (ssPreInstall, ssInstall, ssPostInstall, ssDone);`

used by:
```pascal
procedure CurStepChanged(CurStep: TSetupStep);
```
I'm not sure what is the exact definition of this one.

**Comment by martijnlaan** [comment]
CurStepChanged is never called with CurStep being ssPreInstall.
