### ISSUE TITLE
[feature request] Add SHA-256 hashing support

### ISSUE THREAD

**Issue by dajester2013** [jrsoftware/issrc#157]
I have a requirement to generate a SHA-256 hash during installation, but have not been able to find a means of doing so.  There is a GetSHA1OfString, but nothing higher.  There are multiple Pascal libraries that do more advanced hashing, but I have yet to figure out how to incorporate them into my project.

**Comment by martijnlaan** [comment]
To avoid bloating, [Code] only exposes built in functionality and there's no built in SHA-256 code.
