### ISSUE TITLE
Security Issue: Option to exclude entries from log file

### ISSUE THREAD

**Issue by robertwigley** [jrsoftware/issrc#159]
There needs to be a way to hide certain entries from displaying in the log file, as if, for example, a command in the [Run] section contains a password, the password is displayed in the log file which is a security concern.
http://stackoverflow.com/questions/27864638/inno-setup-hide-a-log-entry

Additionally, there needs to be way of hiding the Setup command line from displaying in the log file, as if passing a password in from the command line, it is then displayed in the log file.
http://stackoverflow.com/questions/26629742/inno-setup-suppress-setup-command-line-log-entry

**Comment by martijnlaan** [comment]
That wouldn't add security in any way. For example, Task Manager shows the command line of running processes.
