### ISSUE TITLE
StrToVersionNumbers() Windows 10 Problem

### ISSUE THREAD

**Issue by mmonsterski** [jrsoftware/issrc#160]
Hello

StrToVersionNumbers() function return only one digit in Major Version - This is a problem for Windows 10 with two digit Major number ex. "10.0.9926.0"

**Comment by DeeHants** [comment]
Has Windows 10 actually been bumped up to major version 10 now?
I guess having such a large disparity between OS version and the name was getting confusing!

**Comment by mmonsterski** [comment]
http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install/windows-10-which-version-should-be-reported/a0561347-c9d9-45a8-a6b6-a30a5faf80e6

**Comment by martijnlaan** [comment]
I assume you mean setting something like MinVersion to 10.0.9926.0 since you can't call StrToVersionNumbers directly. But 10.0.9926.0 is an invalid setting for MinVersion, see the help file.

Iow, no, StrToVersionNumbers does not return only one digit in Major Version.
