### ISSUE TITLE
AppPublisherURL and AppSupportURL are mapped incorrectly.

### ISSUE THREAD

**Issue by BrianKassay** [jrsoftware/issrc#162]
Setting a URL string to AppPublisherURL is showing as 'Support link' when installed and viewed in  Windows Programs and Features.

Setting a URL string to AppSupportURL is showing as 'Help link' in deployments.

**Comment by martijnlaan** [comment]
AppPublisherURL goes to the URLInfoAbout registry key. AppSupportURL goes to the HelpLink registry key. This seems correct to me though I agree the labels your ARP shows are odd.

**Comment by DeeHants** [comment]
They are odd. Windows 7 uses labels `URLInfoAbout` as "Support link:"
![P&F links](https://cloud.githubusercontent.com/assets/1443298/7831327/a8834b00-044d-11e5-9691-868204b0ad37.png)
