### ISSUE TITLE
Support creating hardlinks, directory junctions and symbolic links

### ISSUE THREAD

**Issue by sschuberth** [jrsoftware/issrc#165]
Please add some Pascal script helper functions to easily create [hardlinks](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363860%28v=vs.85%29.aspx), [directory junctions](https://msdn.microsoft.com/de-de/library/windows/desktop/aa365503%28v=vs.85%29.aspx) and [symbolic links](https://msdn.microsoft.com/en-us/library/aa363866.aspx).

**Comment by martijnlaan** [comment]
Only functionality used/needed by IS itself can be exposed to the script. All other stuff you will need to call the Windows API for.

**Comment by sschuberth** [comment]
Hmm, you are saying it's technically impossible to have some kind of "default include" that provides some convenience functions to the `[Code]` section?

**Comment by DeeHants** [comment]
"Default include" of what? Those functions don't exist yet so someone would have to write them, THEN explicitly add them to the scripting support functions.

**Comment by sschuberth** [comment]
Quite obviously, yes. This feature request is about writing these scripting support functions. How they should be made available to the `[Code]` section is a more or less irrelevant implementation detail IMO.

**Comment by martijnlaan** [comment]
You can write those yourself, you don't need a feature request for this.

**Comment by sschuberth** [comment]
But that's what feature requests are all about: Request a feature to be implemented without writing it yourself.

Recently, I've seen that you're very quick at closing issues, in particular feature requests. If you don't intend to actively further develop IS and only accept bug reports to do maintenance, please clearly say so in the README on the front page.

**Comment by martijnlaan** [comment]
Not really, it just that most requests are of low quality, like this one. This happens because most people don't follow the guidelines even though GitHub displays a big box with a link to them after you click the New Issue button.
