### ISSUE TITLE
Script Wizard should default to single icon

### ISSUE THREAD

**Issue by uecasm** [jrsoftware/issrc#168]
Since the standard Windows application guidelines strongly recommend only installing a single icon per application, without putting it into a folder, it would be good if the Script Wizard were updated to reflect this.  (Especially because Windows 8 doesn't respect folder hierarchies anyway.)

Specifically, the default selection in the page dealing with the Start Menu should result in generating `{commonprograms}\{#MyAppName}` instead of `{group}\{#MyAppName}`, and in this configuration it should not be permitted to add readme/uninstall shortcuts.

However, the wizard should still allow selecting the "old style" grouping, in which case these extra icons could be generated, same as currently.

**Comment by martijnlaan** [comment]
I agree but I think the following should then also be changed:
-DisableProgramGroupPage should default to yes instead of no if DefaultGroupName is not set
-IS's own Setup should also be updated to just install a single icon on the start screen

**Comment by uecasm** [comment]
Agreed.

That reminds me: I would also prefer that `DisableProgramGroupPage` (and `DisableDirPage`) default to `auto` from the wizard.  (Ideally they should default to `auto` in the compiler, but Jordan didn't want to do that as it presented a behavioural change for scripts that didn't define a value.)  Using `auto` makes it harder for the user to break Inno's uninstall tracking on upgrades, where the application author hasn't explicitly thought about allowing side-by-side installations.  (Technically this is a separate issue though... let me know if you want me to post it as such.)

**Comment by martijnlaan** [comment]
> I would also prefer that DisableProgramGroupPage (and DisableDirPage) default to auto from the wizard.

For `DisableProgramGroupPage=auto` you meant only when "old style" grouping is used right?

>Ideally they should default to auto in the compiler, but Jordan (...)

I was actually the one who added `auto`. But yes, this is a separate issue.

**Comment by uecasm** [comment]
> For `DisableProgramGroupPage=auto` you meant only when "old style" grouping is used right?

Right.

> I was actually the one who added `auto`. But yes, this is a separate issue.

I thought I recalled Jordan saying something about compatibility when I asked about the default in the newsgroups many moons ago.  But it's possible that I'm just misremembering.

So did you want me to post it as a separate issue?  While they're for different reasons, they both affect the wizard (and one of the same settings thereof).

**Comment by martijnlaan** [comment]
No it's ok, thanks.

**Comment by martijnlaan** [comment]
Just for reference, the relevant guidelines from https://msdn.microsoft.com/en-us/library/windows/desktop/jj673981.aspx:

>DON'T: Don't put shortcuts to the following items on the Start screen: Uninstallers (...) Web sites.

These two extra shortcut options are already unchecked by default in the wizard so that's ok but the end result when both are unchecked is a single Start Menu shortcut and for this is says:

>DON'T: Don't create a product folder if your suite contains only a single shortcut. Place your shortcut in the top-level Start folder.

So that's why we need the new option to disable Start Menu folder creation. Alternatively it could completely disable the folder UI if the two extra shortcut options are unchecked but that's less friendly for when the script user want to add shortcuts to additional executables later on which is ok under the guidelines:

>DO: If you install a suite of apps rather than a single app, add one shortcut for each app in the suite.

**Comment by martijnlaan** [comment]
BTW I noticed if you check "the application doesn't have a main executable" and unchecked the uninstaller & web options, you will get a Start Menu folder with no icons.

**Comment by martijnlaan** [comment]
BTW

>DON'T: Don't create a product folder if your suite contains only a single shortcut. Place your shortcut in the top-level Start folder.

This does not agree with your suggestion to use `{commonprograms}` since that's not the 'top-level Start folder'. Instead it seems to say `{commonstartmenu}` should be used.

**Comment by martijnlaan** [comment]
Uploaded a test build to www.xs4all.nl/~mlaan2/ispack/isetup-5.5.7-dev.exe

**Comment by uecasm** [comment]
Definitely do NOT use `{commonstartmenu}`.  That's for the user's pinned icons.  `{commonprograms}` is the correct location.
