### ISSUE TITLE
Inject custom include file similar to the way ISPPBuiltins.iss works

### ISSUE THREAD

**Issue by extensia** [jrsoftware/issrc#173]
It would be very useful to have a pre-processor option for injecting a user supplied include file into a script similar to the way ISPPBuiltins.iss is added by the pre-processor. The use-case is to support tighter integration between Inno Setup and external build tools which invoke Inno Setup as part of a larger build process. This would enable a build runner to generate an include file on the fly containing build parameter #defines and have Inno Setup include the file automatically without requiring the user to explicitly add a #include statement to the script.

I believe the implementation of this feature would be straightforward, but wanted to solict feedback before working on a pull request to add this feature. Any feedback good or bad would be appreciated.

I currently have a working plugin for the Gradle build tool that we are using for automated Delphi, C# and Java builds. I am considering open sourcing the plugin if there is sufficent community interest to justify the effort.

Regards,
David

**Comment by DeeHants** [comment]
The DLL method of building a setup (used by ISCC and the IDE internally I believe) requires callers to feed in the script line by line, allowing the caller to modify it on demand.

An alternative method in your case is to have your "`#include`" file `#define` everything required THEN `#include` the original script. Your build tool then needs to compile the generated file.

**Comment by extensia** [comment]
Deanna,

Thanks for the feedback. I had considered that option, but was not sure whether I would get into trouble with relative paths. Would the paths within the wrapped script still be relative to the script file location or the wrapper script location? I suspect the former, but have not verified that to be the case.

The requirement for well-behaved continuous integration projects is that the build process should only create files within the /build directory. Writing or modifying files in the /src folder structure where the Inno Setup script lives would pollute the SCM working copy. Best case the CI server would be able to automatically revert the changes (e.g. TeamCity swabra plugin). Worst case, the working copy would need to be recreated before each build rather than incrementally updated.

An alternate approach I considered was to wrap the standard ISPPBuiltins.iss file. Inno Setup would automatically include the "ISPPBuiltins.iss" wrapper script which in turn would include the original renamed script (e.g. "_ISPPBuiltins.iss"). This solves the working copy polution problem since Inno Setup is downloaded and installed as a transient build dependency and lives in a subfolder in the /build directory.

Both approaches appear to be workable, but seem a bit hackish. Injecting the custom include file up front using the same mechanisn as ISPPBuiltins.iss seems like a more elegant approach. Whatever approach is used, the goal is to keep the process as transparent as possible and to retain the ability to easily use Inno Script Studio for development.

**Comment by DeeHants** [comment]
What sort of things will it be injecting? Most values can be injected via ISPP `#define`s which can use default values if not specified.
If the build system needs control of specific features then it probably has custom support for Inno in which case the DLL method would work best.
Check out my [`InnoCompiler.cs`](https://earlsoft.kilnhg.com/Code/BuilderPro/Extensions/Inno/Files/InnoCompiler.cs) and [`CompileInnoScript.cs`](https://earlsoft.kilnhg.com/Code/BuilderPro/Extensions/Inno/Files/CompileInnoScript.cs) for examples.

**Comment by martijnlaan** [comment]
I don't really understand why you would want to inject an extra header if the script isn't going to use anthing from it anyway because it doesn't know about it. But if it's about the name & location of the extra file then the script file could contain this:
```
#ifdef BuildTool_ExtraFile
#include BuildTool_ExtraFile
#endif
```
And then from the commandline you would do something like `"/DBuildTool_ExtraFile=c:\mypath\extrafile.iss"`

**Comment by extensia** [comment]
The DLL mode is not a good option since Gradle is a Java/Groovy based tool. I could write a JNA/JNI shim library, but that would be a non-starter for 64-bit JVM versions which are prevalent these days.

The goal of #include injection is to have the defines generated by the Gradle plugin be available in the script without the user having to explicitly specify the magic include file name chosen by the Gradle plugin. The user knows the #defines being generated by Gradle since they are visible in the Gradle build script and log output.

With the exception of #include injection, I have Inno Setup running in Gradle for Java, C# and Delphi builds and it works extremely well. The convention-over-configuration approach offered by the Gradle DSL makes build scripts very concise and passing of parameters into Inno Setup easy and transparent. A large portion of the repetitive configuration logic normally in our Inno Setup scripts is no longer needed!

**Comment by martijnlaan** [comment]
Ok I understand now. A new command line parameter could be added to ISCC for this. Using the command line parameter you would specify an extra file or files to be included right after ISPPBuiltin.iss is included. Feel free to work on a pull request to add this feature like you said, thanks in advance.

**Comment by extensia** [comment]
Thanks. I am out on vacation until first week of August, but will look into creating a patch when I return. The challenge I have is not having my environment setup to work with the older versions of Delphi. I did manage to get a build working using Delphi 7, but I see there is an issue with Widestring in that version. Would Delphi 5 work better? I also have that version available in a backup image from an old workstation.

**Comment by martijnlaan** [comment]
Ok, cool. I would recommend you just focus on Unicode Inno Setup and forget about ANSI Inno Setup which requires the really old Delphi versions. So you would just need Delphi 2009 with Update 3 then. If you prefer some other version I can check whether the source is compatible with it.

If the finaly patch then doesn't compile under ANSI Inno Setup I will fix it for you.

Make sure you fully read and understand README.md, especially the source code tips. If something is unclear, please ask.

To work with the Delphi 2009 IDE under Windows 8.1 you need these two things to make it work well:
https://dl.dropboxusercontent.com/u/5527765/Delphi_2007_2009_WOW64_Debugger_Fix.exe
https://dl.dropboxusercontent.com/u/5527765/dzEditorLineEndsFix.exe
But you could also avoid the IDE enitrely and just run `compile-unicode.bat` followed by `files\iscc setup.iss /q /DNOSIGNTOOL` which gives an Output\Setup.exe.

Have a nice vacation btw :)

**Comment by martijnlaan** [comment]
Made it support XE8 compilation, see 063b58cc97836a18984d26afd36aa9dfaf248d44 for full notes.
