### ISSUE TITLE
Allow scriptable parameters in Run section

### ISSUE THREAD

**Issue by sagamusix** [jrsoftware/issrc#176]
After installation, I'd like to launch my application with a random example file. Right now, it does not seem to be possible to call a pascal function in the Parameters: section of a [Run] entry, so I have to create the entire run entry manually through code. It would be nice if it was directly possible to use the result of a pascal function for the Parameters and maybe even Filename section.

**Comment by DeeHants** [comment]
This is already available using [`{code:...} constants`](http://www.jrsoftware.org/ishelp/topic_scriptconstants.htm).
"[Constants](http://www.jrsoftware.org/ishelp/topic_consts.htm)" can be used anywhere where the help says something along the lines of:
> ...[which can include constants.](http://www.jrsoftware.org/ishelp/topic_runsection.htm#Parameters)

**Comment by sagamusix** [comment]
Oh, thanks, I was completely not aware of that feature!
