### ISSUE TITLE
Adding a checkbox to the run list programmatically also runs other items

### ISSUE THREAD

**Issue by sagamusix** [jrsoftware/issrc#177]
Here's a minimal script to reproduce the issue.
```
[Setup]
AppVerName=Test
AppVersion=1.0
AppName=Test
DefaultDirName={pf}\Test App
AllowNoIcons=yes
OutputDir=.\
OutputBaseFilename=TestInstall
CreateUninstallRegKey=false
Uninstallable=false
DisableWelcomePage=yes

[Files]
Source: minimal.iss; DestDir: {app}; Flags: ignoreversion

[Run]
Filename: "{app}\minimal.iss"; Description: "View File"; Flags: shellexec nowait postinstall skipifsilent

[Code]

procedure CurPageChanged(CurPageID: Integer);
begin
    if CurPageID=wpFinished then
        WizardForm.RunList.AddCheckBox('Test Box', '', 0, True, True, False, False, nil);
end;

```
Put this in a file called minimal.iss (just so that the script will install itself).
On the Finished page, there will be two checkboxes, "View File" and "Test Box". Test Box should do nothing in this example, and even when it does something sensible, the bug still happens. However, both checkboxes will launch the minimal.iss file in this example. So if both boxes are checked, the file will even be launched twice.
Since AddCheckBox has no documentation, it might be an issue on my side (but a quick search on the internet seemed to confirm that the function should be used like this), but it might as well be an actual bug.

**Comment by martijnlaan** [comment]
Hacking into IS's own controls like that is in no way supported. You should use a [Run] entry for the extra checkbox. If you don't know how you should ask for help on the newsgroups.
