### ISSUE TITLE
Unlock LZMA2 compatibility: Allow LZMADictionarySize/LZMABlockSize bigger than 262144 in LZMA2

### ISSUE THREAD

**Issue by rkkoszewski** [jrsoftware/issrc#179]
LZMA has as limit 262144 (*256MB*) for its *DictionarySize*, but *LZMA2* goes up to *1GB*. The same for *LZMABlockSize* where *LZMA2* supports up to *64GB or Limitless*.. 

With everything maxed out in Inno Setup (**LZMADictionarySize**:262144 (*256MB*) and **LZMABlockSize**:262144 (*256MB*)) I get a **3.8GB** installer.

But using *7zip* with the same files I use in the setup (and some more that are not included in the setup) using a **Dictionary size** of **512MB** and a **Block Size** of **4GB** (Still haven't tried to use the Unlimited Option) I get a file **2.7GB**..

As far as I'm aware a 512MB dictionary requires 512MB of RAM on the target computer to decompress the files, which is fine for my target users.

**Is it possible to unlock the 262144 limit for LZMA2 in Inno Setup? Or is it some kind of design flaw/limit in Inno Setup?**

Please note: In both I was using Word size of 64 and 1 CPU thread.

**Comment by martijnlaan** [comment]
I don't know if the limits you mention are correct for each version of LZMA and for the version of the SDK used by Inno Setup and all the related files. Checking this is very hard since there's so many files related to this:

https://github.com/jrsoftware/issrc/tree/master/Projects/Lzma2
https://github.com/jrsoftware/issrc/tree/master/Projects/LzmaDecode
https://github.com/jrsoftware/issrc/blob/master/Projects/LZMA.pas
https://github.com/jrsoftware/issrc/blob/master/Projects/LZMADecomp.pas
https://github.com/jrsoftware/issrc/blob/master/Projects/LZMADecompSmall.pas.

I can tell right away a blocksize of 4 GB won't work since it uses an signed 32 bit integer to pass the size around. So no, I can't simply 'unlock' the dictionary and block size limits. Do you have a proposal for a more modest increase of the limits which would still help your file size?

**Comment by rkkoszewski** [comment]
Hi, thanks for looking at this.

Related to the block size:
How far would it be possible to get here? with a signed 32 bit integer you could theoretically get to a block size of 2GB if I'm not wrong, which would be anyway a huge compression efficiency boost in comparison with the current 256MB limit. Even 512MB or 1GB block size would be already better.

Related to the dictionary size:
How far would it be possible to get here too? Doubling the current amount of 256MB to 512MB can have a great amount of compression impact.  

Here is what I've found from the LZMA-Specification (http://www.7-zip.org/a/lzma-specification.7z) from the LZMA SDK (http://www.7-zip.org/sdk.html):

	...
	The dictionary size in LZMA2 is encoded with just one byte and LZMA2 supports
	only reduced set of dictionary sizes:
	  (2 << 11), (3 << 11),
	  (2 << 12), (3 << 12),
	  ...
	  (2 << 30), (3 << 30),
	  (2 << 31) - 1
	...
	LZMA supports dictionary sizes up to 4 GiB minus 1.
	...

Would it be posible to have this improvement considered to be included in Inno Setup?

**Comment by martijnlaan** [comment]
I should be able to up the max dictionary size to 1 or 2 GB pretty easily at least.

You request about ``LZMABlockSize`` I don't really understand: if you're after maximum compression I would expect you to be using ``LZMANumBlockThreads=1`` (the default), in which case ``LZMABlockSize`` does nothing, see http://www.jrsoftware.org/ishelp/index.php?topic=setup_lzmablocksize. Maybe you're confusing the block size setting (called chunk size in the 7-zip help file) with the solidbreak flag (similar to what's called solid block size in the 7-zip file).

**Comment by rkkoszewski** [comment]
Hi,
Yes it seems I misunderstood how `LZMABlockSize `works.  I use indeed `LZMANumBlockThreads=1 `and I thought that `LZMABlockSize `would affect the amount of files that can be compressed into one block (Even if it's single threaded). So the huge compression boost seems to be just because of the dictionary size. 

It would be really useful if the dictionary size increase could be considered to be implemented into Inno Setup.

**Comment by martijnlaan** [comment]
I will try increasing its limit to 1 GB. 2 GB seems impossible: unless I misunderstand it, a 2 GB dictonary size means the decoder (=Setup) would need 2 GB memory just for decompression but Setup is a 32 bit process so that's too much.

**Comment by rkkoszewski** [comment]
1GB of dictionary size limit (even 512MB would do it) are just awesome news. Thanks for the consideration. This will be very handy.

**Comment by martijnlaan** [comment]
Test builds:
https://www.xs4all.nl/~mlaan2/isetup-5.5.9-dev.exe
https://www.xs4all.nl/~mlaan2/isetup-5.5.9-dev-unicode.exe

**Comment by rkkoszewski** [comment]
Thanks a lot! Seems to be working pretty well. By using 512 MB my Installer shrunk 3.5 GB instead of 3.8 GB. The source data is of 11.5 GB of size, so I have to say that the compression ratio is outstanding. 

So my results for now:
Compilation with a dictionary size of 512 MB was successful. The resulting setup file (3.5GB) installed without any issues.

Tomorrow I'll try with 768 MB, and I'll post here the results.

**Comment by rkkoszewski** [comment]
Wow.. 3.18 GB with 1GB of dictionary size. Compilation and Installation both were successful. :+1: 
Thanks!!!
