### ISSUE TITLE
Inno Setup does not close system tray (window less) application when reinstalling

### ISSUE THREAD

**Issue by sthammadi-spsc** [jrsoftware/issrc#181]
Hi,

I'm using the latest Inno Setup (5.5.6) to package my application (.NET based) which has 2 main exe's.
One is a Winform application (when minimized goes to system tray) and the other is a window less application (starts as a ApplicationContext and is in system tray as well).

When both are running and I try to reinstall, the winform application gets killed and respective tray icon removed, but the window less application doesn't get killed, but the tray icon is removed.

Not sure what's going wrong here.

I have also set the PrivilegesRequired is 'admin', in case this was related to access issue. Also the CloseApplications flag is 'yes'

Please help !

Cheers,

**Comment by martijnlaan** [comment]
Please use the newsgroup for questions, thanks.
