### ISSUE TITLE
BitmapImage.pas(250) Error: Undeclared identifier: 'CopyPalette'

### ISSUE THREAD

**Issue by rkkoszewski** [jrsoftware/issrc#184]
I get an error while compiling - Setup.dpr:

**C:\Program Files\Borland\Delphi 2.0\Lib\BitmapImage.pas(250) Error: Undeclared identifier: 'CopyPalette'
NewDisk.pas(20) Fatal: Could not compile used unit 'BitmapImage.pas'**

All libraries seems to be installed and everything is being compiled successfully till it compiles Setup.dpr. I'm compiling it under Windows 10 and Windows 7 (In Virtual Machine). I get the same error in both.

I've been looking in the GRAPHICS.DPR file in the Delphi 2.0\Lib folder, and it has the function "CopyPalette" inside. So it should theoretically work..

Somebody knows how I could get it to work? Any ideas? 
Thanks..

**Comment by martijnlaan** [comment]
I don't have a suggestion except that BitmapImage.pas shouldn't reside in your Delphi's Lib dir.
