### ISSUE TITLE
"Check" function for [UninstallDelete] is invoked when Installing and not when Uninstalling

### ISSUE THREAD

**Issue by engycz** [jrsoftware/issrc#185]
"Check" function for [UninstallDelete] is invoked when Installing and not when Uninstalling.
See attached sample project. Hello is shown when installing and not shown when uninstalling

[Test.iss.txt](https://github.com/jrsoftware/issrc/files/33898/Test.iss.txt)

**Comment by DeeHants** [comment]
That's behaving as designed, and `check` parameters are used to conditionally install something, with the associated uninstall entries.

Inno doesn't support uninstall time Check parameters.

If you need to ask a question at uninstall time, you'll need to do it in `[Code]`, probably
the `CurUninstallStepChanged` event function.
