### ISSUE TITLE
SIgntools SHA-1 and SHA256 - error

### ISSUE THREAD

**Issue by pavel-pimenov** [jrsoftware/issrc#187]
try
SignTool=signppafly5
SignTool=signppafly5sha256

[Setup] section directive "SignTool" already specified :-(

Please fix this bug (For code signing certificates, Windows will stop accepting SHA-1 signed code and SHA1 certificates that are time stamped after 1 January 2016. SHA-1 signed code time stamped by an RFC 3161 Time Stamp Authority before 1 January 2016 will be accepted until such time when Microsoft decides SHA-1 is vulnerable to pre-image attack.)

"C:\Program Files (x86)\Windows Kits\8.1\bin\x86\signtool.exe" sign /?

Signing parameter options:
/as         Append this signature. If no primary signature is present, this
            signature will be made the primary signature instead.

Command line - all ok:

"C:\Program Files (x86)\Windows Kits\8.1\bin\x86\signtool.exe" sign /v /d "FlylinkDC++ r5xx" /du "http://flylinkdc.blogspot.com" /fd sha1 /t http://timestamp.verisign.com/scripts/timstamp.dll ".\compiled\FlylinkDC.exe"
"C:\Program Files (x86)\Windows Kits\8.1\bin\x86\signtool.exe" sign /as /v /d "FlylinkDC++ r5xx" /du "http://flylinkdc.blogspot.com" /fd sha256 /tr http://timestamp.comodoca.com/rfc3161 /td sha256 ".\compiled\FlylinkDC.exe"

**Comment by martijnlaan** [comment]
Perhaps you meant this as a feature request, obviously this is not a bug. You can define only one SignTool. Use a batch file. Feel free to make a feature request but when you do please explain why you can't just have the signppafly5sha256 tool and still need the signppafly5 tool.

**Comment by pavel-pimenov** [comment]
Thanks. 
The first signing uses SHA1 for Windows XP
second uses SHA256 for Windows7/8/10

http://stackoverflow.com/questions/18542160/signtool-failing-to-dual-sign-sha2-and-sha1-with-timestamps
