### ISSUE TITLE
Exec returns confusing ResultCode 259

### ISSUE THREAD

**Issue by mcbsys** [jrsoftware/issrc#190]
I finally figured this out. A couple documentation tweaks could help avoid confusion.

When you use Exec with ewNoWait or ewWaitUntilIdle, the ResultCode will be 259. The Help says "Use SysErrorMessage(ResultCode) to get a description of the error," but for 259, that returns the text "No more data is available."

If I am reading the source code correctly, Exec calls InstExec. On failure, the ResultCode comes from GetError, but on success, InstExec calls HandleProcessWait, which sets ResultCode from the Windows API function [GetExitCodeProcess](https://msdn.microsoft.com/en-us/library/ms683189%28v=vs.85%29.aspx). This gets the *exit code of the called process*, which does not correspond to the standard Windows system errors retrieved from SysErrorMessage. Also, GetExitCodeProcess reserves one exit code for its own use:  259 means STILL_ACTIVE, i.e. the process hasn't exited yet, so no exit code is available. In other words, when using ewNoWait or ewWaitUntilIdle, ResultCode 259 is expected.

ShellExec calls InstShellExec, which explicitly sets STILL_ACTIVE before calling HandleProcessWait, so the same confusion would probably arise. 

ISPP has a slightly different implemenation of Exec, so I'm not sure whether this applies there.

Perhaps the documentation for Exec and ShellExec could be updated as follows:

> If True is returned, then ResultCode specifies the exit code of the called process, except that ResultCode 259 is a reserved code indicating that the process is still active. In other words, ResultCode is only meaningful after the process exits, which only happens if TExecWait is ewWaitUntilTerminated. When TExecWait is ewNoWait or ewWaitUntilIdle, the installer continues while the process is still running; in this case, no exit code is available and ResultCode 259 is expected.

> If False is returned, then ResultCode specifies the error that occurred. Use SysErrorMessage(ResultCode) to get a description of the error.

**Comment by martijnlaan** [comment]
The help file already clearly identitifies the two cases in which ResultCode is defined: "If True is returned and Wait is ewWaitUntilTerminated then ResultCode returns the exit code of the process. If False is returned then ResultCode specifies the error that occurred.". You're looking at ResultCode in another case so it should be no surprise that ResultCode is neither the exit code nor the error?

**Comment by mcbsys** [comment]
I see your point. My confusion was that that I interpreted the final sentence ("Use SysErrorMessage(ResultCode) to get a description of the error.") as applying to both True and False. A couple line breaks would fix that:

>Executes the specified executable or batch file, using the same credentials as Setup/Uninstall. The Wait parameter specifies whether the function should return immediately or wait until the launched process has terminated or is idle. Returns True if the specified file was executed successfully, False otherwise. 
>
>If True is returned and Wait is ewWaitUntilTerminated then ResultCode returns the exit code of the process. 
>
>If False is returned then ResultCode specifies the error that occurred. Use SysErrorMessage(ResultCode) to get a description of the error.

**Comment by mcbsys** [comment]
Thanks! That should help.
