### ISSUE TITLE
[Feature request] Hide passwords from log

### ISSUE THREAD

**Issue by peen** [jrsoftware/issrc#191]
There are great logging possibilities which are in Innosetup. This is OK. Logging could be:
- implicite (like logging commands which are run)
- explicite - using Log function
- maybe other which I am not aware of

Sometimes passwords must be hidden from resulting log, for example for security reasons.

I would like to suggest the solution for the above requirement (if accepted):
 - introduce setup event function BeforeLog(LogString : String) which could be fired just before logging the string into log file. It would give a possibility to replace a password string with, for example, "***********" string

**Comment by martijnlaan** [comment]
Please use the newsgroup before posting feature requests, like the guidelines say. This request doesn't make a lot of sense to me, the password is only logged if you use the command line and it that case it's also visible in other places like the Task Manager. Additionally the logging is controlled by yourself. So no security is added.
