### ISSUE TITLE
 Access violation at address 773A12A4 in module 'ntdll.dll'. Read of address 00000000.

### ISSUE THREAD

**Issue by pankaj19** [jrsoftware/issrc#192]
I am getting this error " Access violation at address 773A12A4 in module 'ntdll.dll'. Read of address 00000000." while installing application in Windows 2012 in Japanese Language. Below are the last line of logs:
2016-01-06 12:08:57.902   Exception message:
2016-01-06 12:08:57.902   Message box (OK):
                          Access violation at address 773A12A4 in module 'ntdll.dll'. Read of address 00000000.

I am using Inno unicode 5.5.6 version for creating the installer.

**Comment by martijnlaan** [comment]
Sorry but nothing can be done with this without at least a script which reproduces the problem on a system I can access.
