### ISSUE TITLE
Make IsComponentSelected available at uninstall time

### ISSUE THREAD

**Issue by kuniss** [jrsoftware/issrc#193]
Currently (InnoSetup version 5.5.6), an internal error is raised if function `IsComponentSelected` is called during uninstall time.

It would be very helpful for component based software systems (such one which spreads the InnoSetup logic to functional components too) having the mentioned method available at uninstall time.

E.g., what I want to achieve is a component dependent run of restart logic during uninstall where the component developer decides whether a restart is needed by implementing a component specific function which returns the decision value. The global installer scripts aggregates these methods as follows:
```pascal
function UninstallNeedRestart(): Boolean;
begin
  try 
  result := result or (IsComponentSelected('component1') and component1_UninstallNeedRestart());
  result := result or (IsComponentSelected('component2') and component2_UninstallNeedRestart());
  result := result or (IsComponentSelected('component3') and component3_UninstallNeedRestart());
  except
    // Catch the exception, show it, and continue
    ShowExceptionMessage;
  end;
end;
```

in that way, the restart is only then triggered if the particular component was selected at install time. That's where the need for `IsComponentSelected` comes in.

**Comment by martijnlaan** [comment]
Ok, I understand. A workaround for now is that you could read the selected components yourself from the 'Inno Setup: Selected Components' value in the uninstall registry key.

**Comment by uecasm** [comment]
In general it is better to detect component presence at uninstall time by looking for corresponding files or registry entries, rather than using `IsComponentSelected` or parsing the uninstall value.

This is because the user might deselect the component in a subsequent upgrade, which will remove the component from the registry but the (old) files will still be present on disk, and the application will likely treat the component as still installed.

**Comment by martijnlaan** [comment]
Agreed, thanks.

**Comment by kuniss** [comment]
@uecasm: Did I understand right, that if a component gets deselected on a subsequent upgrade, this component gets unregistered from the InnoSetup persisted installation status (I guess, in the registry). However, the files already installed for that component remains on disk?
If so, is there an API function in InnoSetup framework available, which returns the aggregated set of components installed in the past of the life time of the current installation instance including all upgrades?

**Comment by uecasm** [comment]
@kuniss: That is correct, and no, there is not.  This is why examination of which files are present on disk is the most robust way to determine if a component has ever been installed.  (Presumably, as the setup author, you know at least one file that is unique to a particular component of interest.)

Note that the UninsHs third party addon provides support for actually removing the files corresponding to a component when the component is deselected; I haven't looked into exactly how it does this but I assume it forces an uninstall and reinstall.  (This is naturally less efficient.)
