### ISSUE TITLE
[feature request]Allow multiple SignTool entries

### ISSUE THREAD

**Issue by ash-tsc** [jrsoftware/issrc#194]
Being able to append SHA 256 additionally to SHA 1 would help.

See:
https://knowledge.symantec.com/support/code-signing-support/index?page=content&actp=CROSSLINK&id=INFO2274
because:
https://knowledge.symantec.com/support/code-signing-support/index?page=content&id=INFO3199&actp=search&viewlocale=en_US

MS:
http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx

**Comment by martijnlaan** [comment]
I just finished this. See https://github.com/jrsoftware/issrc/commit/42e2cfbad2f805dbfd2efaffbb779909bab999ed

Thanks for sending the above links to me earlier via email.

Before you ask: I don't know when 5.5.8 will be released but I can upload a dev build if you want.

**Comment by martijnlaan** [comment]
BTW the MS link says under Enforcement details: "Code signing signatures: No changes until SHA-1 preimage is possible" so not sure this is actually needed already?

**Comment by martijnlaan** [comment]
Dev builds can be found here: (both dual signed)
http://mlaan2.home.xs4all.nl/isetup-5.5.8-dev.exe
http://mlaan2.home.xs4all.nl/isetup-5.5.8-dev-unicode.exe

**Comment by ash-tsc** [comment]
Thank you, works as expected! 
:)
http://snap.ashampoo.com/9RENzN2E

Note: 
Make sure to use a current version of signtool.exe (which is part of windows sdk) 
/as parameter is not (!) available in older builds 

https://knowledge.symantec.com/support/code-signing-support/index?page=content&id=AR2274

**Comment by martijnlaan** [comment]
Thanks for testing. That /as is new is already noted in the SignTool help file topic.

**Comment by ash-tsc** [comment]
Dear Martijin, thank you for Inno Setup 5.5.8 release! :)

**Comment by martijnlaan** [comment]
You're welcome. BTW see the newsgroup, the instructions from Symantec you linked above are wrong, a `/td sha256` parameter is missing.
