### ISSUE TITLE
Folder deleted from uninstall, but explore gives a warning instead of closing the window on Windows 2012

### ISSUE THREAD

**Issue by pankaj19** [jrsoftware/issrc#196]
We are facing an issue on Windows 2012, when we are performing uninstall operation from inside the installed location (like c:\program files\<group_name>\<app>), uninstall is complete with windows pop up error that location "c:\program files\<group_name>" not found.

Expected behaviour should be either windows explore is close or move the to parent or one level up that is "C:\program files".

We are using Inno 5.5.6 unicode verison.

**Comment by martijnlaan** [comment]
Please use the newsgroup for questions. You should use ARP to start the uninstaller.

**Comment by pankaj19** [comment]
Hi Martijnlaan,
Could you please provide more details on ARP or provide any url/link.

**Comment by DeeHants** [comment]
Why is it an Inno bug that Mcrosoft Windows Explorer is showing an error message?
