### ISSUE TITLE
[Feature Request] Right To Left Layout for Arabic Language

### ISSUE THREAD

**Issue by Motaz-Alnuweiri** [jrsoftware/issrc#201]
### Hello :)

I would like to request this feature to make Setup windows right to left as in Arabic version of the Windows itself, I did it via Windows APIs but I can't access all windows and I think it's best to add it to Setup by default.

#### Problem
In Arabic translations file I added `RightToLeft = Yes`:
```
[LangOptions]
...
RightToLeft=yes
```
and the Setup windows will look like this:
![Old Right To Left Layout Image](http://i1297.photobucket.com/albums/ag34/MotazNew/Inno%20Setup/1_zpsj2xg5lho.jpg)

#### Solution
I wrote a code to make the windows as it should be in Arabic:
```pascal
[Code]
// Author: Motaz Alnuweiri
// Copyright (C) 2016 for Motaz Alnuweiri.

#ifdef UNICODE
  #define AW "W"
#else
  #define AW "A"
#endif

// Windows APIs to Set ExStyle Layout
function SetWindowLong(HWND: HWND; nIndex: Integer; dwNewLong: longint): HWND;
  external 'SetWindowLong{#AW}@user32.dll stdcall';
function GetWindowLong(HWND: HWND; nIndex: Integer): longint;
  external 'GetWindowLong{#AW}@user32.dll stdcall';

const
  // Windows ExStyle (nIndex)
  // URL: https://msdn.microsoft.com/en-us/library/windows/desktop/ff700543%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
  GWL_EXSTYLE = -20;
  WS_EX_LAYOUTRTL = $00400000;
  WS_EX_NOINHERITLAYOUT = $00100000;
  WS_EX_RIGHT = $00001000;
  WS_EX_RTLREADING = $00002000;

// On Setup Initialize
procedure InitializeWizard();
var
  ExStyle: Longint;

begin
  // Right To Left Layout for Arabic
  If Not WizardForm.RightToLeft Then
  begin
    ExStyle := GetWindowLong(WizardForm.Handle, GWL_EXSTYLE);
    SetWindowLong(WizardForm.Handle, GWL_EXSTYLE, ExStyle Or WS_EX_LAYOUTRTL 
                  Or WS_EX_NOINHERITLAYOUT xOr WS_EX_RIGHT xOr WS_EX_RTLREADING);
  
    WizardForm.CancelButton.Left := WizardForm.Width - WizardForm.CancelButton.Left - WizardForm.CancelButton.Width;
    WizardForm.NextButton.Left := WizardForm.Width - WizardForm.NextButton.Left - WizardForm.NextButton.Width;
    WizardForm.BackButton.Left := WizardForm.Width - WizardForm.BackButton.Left - WizardForm.BackButton.Width;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ExStyle: Longint;

begin
  If CurUninstallStep = usUninstall Then
  begin
    // Right To Left Layout for Arabic
    If UninstallProgressForm.RightToLeft Then
    begin
      ExStyle := GetWindowLong(UninstallProgressForm.Handle, GWL_EXSTYLE);
      SetWindowLong(UninstallProgressForm.Handle, GWL_EXSTYLE, ExStyle Or WS_EX_LAYOUTRTL 
					          Or WS_EX_NOINHERITLAYOUT xOr WS_EX_RIGHT xOr WS_EX_RTLREADING);

      UninstallProgressForm.CancelButton.Left := UninstallProgressForm.Width 
                                               - UninstallProgressForm.CancelButton.Left 
                                               - UninstallProgressForm.CancelButton.Width;
    end;
  end;
end;
```
and here is the result:
![Fixed Right To Left Layout  Image](http://i1297.photobucket.com/albums/ag34/MotazNew/Inno%20Setup/2_zpstfvduku2.jpg)

**Thank you**

**Comment by martijnlaan** [comment]
Thanks. Can you provide some MSDN links which show this is correct approach?

**Comment by Motaz-Alnuweiri** [comment]
No problem :) , Take a look to this link:
https://www.microsoft.com/middleeast/msdn/mirror.aspx

**Comment by martijnlaan** [comment]
Why does your code do ``xOr WS_EX_RIGHT xOr WS_EX_RTLREADING``, that's just weird. Also note it already does ``Params.ExStyle := Params.ExStyle or (WS_EX_RTLREADING or WS_EX_LEFTSCROLLBAR or WS_EX_RIGHT);`` in TSetupForm, I'm not gonna remove those.

**Comment by Motaz-Alnuweiri** [comment]
As I remember because your own RTL layout it's go's wrong so I add  `xOr WS_EX_RIGHT xOr WS_EX_RTLREADING` .. I will made some test on it.

And here is all supported Windows:

> **System Requirements** 

> Platforms: Arabic Windows 98 (enabled and localized), Arabic Windows Millennium Edition (enabled and localized), Windows 2000, Windows XP Home Edition, Windows XP Professional, Windows .NET Server 2003 family.

**Comment by martijnlaan** [comment]
Ok. Note you should test by updating the ``TSetupForm`` code I listed above instead of doing it later via ``SetWindowLong``.

**Comment by Motaz-Alnuweiri** [comment]
How to do that via `TSetupForm` :D ?

**Comment by martijnlaan** [comment]
You would need to build Inno Setup yourself using Delphi, is that possible?

**Comment by Motaz-Alnuweiri** [comment]
Yes I will do that for you ;) .. But the electricity not help it cut off 12~13 hours every day in Gaza :(

**Comment by Motaz-Alnuweiri** [comment]
Hi @martijnlaan,

After some tests I changed
`Params.ExStyle := Params.ExStyle or (WS_EX_LAYOUTRTL or WS_EX_NOINHERITLAYOUT or WS_EX_LEFTSCROLLBAR);`
in `TSetupForm` but the bottom area flipped wrong.

The result:
![Image 1](http://i1297.photobucket.com/albums/ag34/MotazNew/Inno%20Setup/3_zpsueq5nizr.jpg)

**Solution:**
1. Prevent the controls in this area from flip.
2. When we added `WS_EX_LAYOUTRTL` the Windows will flip all the controls so we don't need any flip procedure but all the controls in `TWizardPage` not flipped, I don't know why ?

And we need to add `WS_EX_LAYOUTRTL or WS_EX_NOINHERITLAYOUT` to
`Params.ExStyle` for `ProgressBar` and `FolderTreeView` when
`RightToLeft` is True like in `TSetupForm`

![Image 2](http://i1297.photobucket.com/albums/ag34/MotazNew/Inno%20Setup/4_zpsybizbtlr.jpg)

![Image 3](http://i1297.photobucket.com/albums/ag34/MotazNew/Inno%20Setup/5_zpsnsqejxnf.jpg)

**Solution:**
1. Get `RightToLeft` value from `LangOptions`.
2. Add `RightToLeft: Boolean` to the constructor of the control.

**Comment by Motaz-Alnuweiri** [comment]
I successfully implement `RightToLeft` layout for `TNewProgressBar` and I did the same to `TCustomFolderTreeView` but it's not changed.

In `NewProgressBar.pas` I add this:
```pascal
private
   FUseRightToLeft: Boolean;
...

procedure TNewProgressBar.CreateParams(var Params: TCreateParams);
  ...
  FUseRightToLeft := SetBiDiStyles(Self, Params);
end;
```

In `BidiUtils.pas` I add modified:
```pascal
function SetBiDiStyles(const AControl: TControl; var AParams: TCreateParams): Boolean;
var
  ClassName: String;

begin
  Result := IsParentRightToLeft(AControl);
  if Result then
  begin
    ClassName := AControl.ClassType.ClassName;
    
    if (ClassName = 'TNewProgressBar') or (ClassName = 'TCustomFolderTreeView') then
       AParams.ExStyle := AParams.ExStyle or (WS_EX_LAYOUTRTL or WS_EX_NOINHERITLAYOUT or WS_EX_LEFTSCROLLBAR)
    else
       AParams.ExStyle := AParams.ExStyle or (WS_EX_RTLREADING or WS_EX_LEFTSCROLLBAR or WS_EX_RIGHT);
  end;
end;
``

**Comment by Motaz-Alnuweiri** [comment]
finally I implement full RightToLeft layout :dart: :smile: , But `TCustomFolderTreeView` is still in wrong layout.

**Comment by Motaz-Alnuweiri** [comment]
I successfully implement full `RightToLeft` layout for Arabic language, I added `WS_EX_LAYOUTRTL` to `TNewProgressBar` and `TCustomFolderTreeView` to make it RTL.

**URLs:**
- https://msdn.microsoft.com/en-us/goglobal/bb688119
- https://www.microsoft.com/middleeast/msdn/mirror.aspx
- https://msdn.microsoft.com/en-us/library/windows/desktop/ff700543%28v=vs.85%29.aspx

**Requirements:**
- Minimum supported client:
  Windows 2000 Professional [desktop apps only]

- Minimum supported server:
  Windows 2000 Server [desktop apps only]
 
**I faced some Problems:**
1. `TCustomFolderTreeView` not effeicted with `WS_EX_LAYOUTRTL` and it's still LTR.
2. `TBitmapImage` will mirrored when added WS_EX_LAYOUTRTL if the parent `is TSetupForm`.

In `NewProgressBar.pas` I added:
```pascal
procedure TNewProgressBar.CreateParams(var Params: TCreateParams);
begin
  ...
  SetBiDiStyles(Self, Params);
end;
```

In `FolderTreeView.pas` I added:
```pascal
procedure TCustomFolderTreeView.CreateParams(var Params: TCreateParams);
begin
  ...
  SetBiDiStyles(Self, Params);
end
```

In `BidiUtils.pas` I modified:
```pascal
function SetBiDiStyles(const AControl: TControl; var AParams: TCreateParams): Boolean;
var
  ClassName: String;
  ExStyle: DWORD;

begin
  Result := IsParentRightToLeft(AControl);
  if Result then
  begin
    { We get (Fatal F2047) when added NewProgressBar and FolderTreeView unit
      to uses section, so we used the class name to check if it's
      TNewProgressBar or TCustomFolderTreeView }
    ClassName := AControl.ClassType.ClassName;

    if (ClassName = 'TNewProgressBar') or (ClassName = 'TCustomFolderTreeView') then
       ExStyle := WS_EX_LAYOUTRTL
    else
       ExStyle := (WS_EX_RTLREADING or WS_EX_LEFTSCROLLBAR or WS_EX_RIGHT);

  AParams.ExStyle := AParams.ExStyle or ExStyle;
  end;
end;
```

In `SetupForm.pas` I modified:
```pascal
procedure TSetupForm.FlipControlsIfNeeded;
var
  I: Integer;

begin
  if FFlipControlsOnShow then begin
    FFlipControlsOnShow := False;
    FControlsFlipped := not FControlsFlipped;

    for I := 0 to Self.ControlCount - 1 do
    begin
      { When added WS_EX_LAYOUTRTL there is no need to flip all controls
        because Windows will flipped it automatically, so we still need
        to flip all controls in TNewsNotebook because it's no effect }
      if Self.Controls[I] is TNewNotebook then
         FlipControls(TWinControl(Self.Controls[I]));
    end;
  end;
end;
```

**Comment by Motaz-Alnuweiri** [comment]
Hello :smile: , are you still there @martijnlaan ?

**Comment by martijnlaan** [comment]
I was away today. I haven't looked at your changes yet, also am unclear if you're done with them or not?

**Comment by Motaz-Alnuweiri** [comment]
It's almost done, But there are 2 problems:
1. `TBitmapImage` is mirrored when set `WS_EX_LAYOUTRTL` the solution is `SetLayout(hdc, 0)` for the canvas as in this ![link](https://msdn.microsoft.com/en-us/goglobal/bb688119) but the image will disappear.
2. `TCustomFolderTreeView` not effeicted with `WS_EX_LAYOUTRTL` and it's still LTR.

**Comment by Motaz-Alnuweiri** [comment]
I'm done @martijnlaan , I can't found solutions for the two problems I mentioned before so it's your turn to help me

**Comment by martijnlaan** [comment]
Are you going to make a new pull request? Not sure how much I can help since I'm not familiar with how RTL is supposed to look/work & not even sure if it will work on my Dutch Windows but I'll try.

**Comment by Motaz-Alnuweiri** [comment]
Yes, It will work fine just use Unicode version of the Setup and add `RightToLeft=yes` to language file or use this [Arabic.txt](https://github.com/jrsoftware/issrc/files/112148/Arabic.txt) Arabic language file.

Yes correct, `TCustomFolderTreeView` was LTR and I changed it but not affected. `TBitmapImage` not supposed to be mirrored I add `SetLayout(hdc, 0)` as Microsoft suggestion but the image disappeared.

**Comment by martijnlaan** [comment]
I didn't do any of the LTR changes myself, so I wasn't the one who added ``WS_EX_LEFTSCROLLBAR`` and I don't know why it's there.

Gonna close this one since there's #205 now.
