### ISSUE TITLE
DeleteFileRedir should check, if deletion was actually successful

### ISSUE THREAD

**Issue by virgoparna** [jrsoftware/issrc#202]
In DeleteFileRedir if  Windows.DeleteFile(PChar(Filename)) result with success there should be a check, if file was actually deleted.
There are cases in Windows, when DeleteFile reports success, but file is not actually closed until all handles to it are close. And that breaks use of restartreplace, because DeleteFileRedir reported success, but later MoveFile fails, because file is still open.

**Comment by martijnlaan** [comment]
Closing since there's a newsgroup thread for this.
