### ISSUE TITLE
Farsi Translation

### ISSUE THREAD

**Issue by heforfree** [jrsoftware/issrc#204]
here an updated Farsi translation.added *.txt at the end of file to upload.please update it
[Farsi.isl.txt](https://github.com/jrsoftware/issrc/files/109906/Farsi.isl.txt)

**Comment by martijnlaan** [comment]
There already is a Farsi translation. If you have fixes, comments or suggestions about it, please contact its maintainer.

**Comment by heforfree** [comment]
hi
as you can see link bellow it updated 10 month ago
i emailed sometime ago in for v 5.5.5.but dont get an email or updated here
if you don't trust email me i send it as email
https://github.com/jrsoftware/issrc/tree/master/Files/Languages/Unofficial

**Comment by heforfree** [comment]
also please make it official

**Comment by heforfree** [comment]
also this just compatible with none right to left installer

**Comment by martijnlaan** [comment]
Do you mean you're Hessam Mohamadi? Please use http://www.jrsoftware.org/files/istrans/send2.php
See http://www.jrsoftware.org/files/istrans/send.php for info about becoming an official translation.

**Comment by heforfree** [comment]
done.thankyou very much
