### ISSUE TITLE
Remove _is1 suffix

### ISSUE THREAD

**Issue by MartinDelille** [jrsoftware/issrc#207]
When specifying the *AppId* parameter to an Inno Setup script, a `_is1` suffix is automatically added: https://github.com/jrsoftware/issrc/blob/41fec0815ada1f84a41485c60f3f7cbbcbe06b4c/Projects/Install.pas#L511

Would it be possible to add an option to disable this suffix?

**Comment by MartinDelille** [comment]
Just adding some explanation: I created an application and used to deploy it with Visual Studio installer which is not so good. I decided to move to Inno Setup and I would like the new script to uninstall the application deployed with the old script.

**Comment by martijnlaan** [comment]
I don't understand how that's related to the _is1 suffix but please use the newsgroup for questions.

**Comment by MartinDelille** [comment]
This was not a question but a suggestion with a user case. But anyway I will just patch it for my specific use. Sorry for the disturbance.

**Comment by DeeHants** [comment]
@MartinDelille The ID used by Inno has no bearing on your ability to remove other applications, and in fact, if they were made the same as your existing app, would cause conflicts and other issues.
If you have a use case for actually making the `_is1` optional, we'd like to hear it.

**Comment by MartinDelille** [comment]
Yes you're right: in fact my original goal was to delete the old app before installing the new. I performed this by running msiexec /x{old app id} in the PrepareToInstall step.

**Comment by mike-cochrane** [comment]
I have struck an issue trying to deploy an application using SCCM where adding the suffix is a problem. When deploying an application one of the steps is setting the detection method for determining the success of the installation. It would be nice to use the installation database which requires a Product Code GUID, unfortunately with the suffix this does not work and we will have to fallback to using a file or another registry key.

**Comment by DeeHants** [comment]
Why can't you just put `_is1` on the end of the ID you give it? It's not guaranteed to be a GUID so it should accept free text.

**Comment by mike-cochrane** [comment]
@deehants unfortunately the SCCM interface only accepts a valid GUID. I haven't tried yet with powershell which is how we will ultimately create the deployment so I'll try that and report back.

**Comment by DeeHants** [comment]
@mike-cochrane then that is broken. Sorry.
The app ID is not guaranteed to be a GUID and the expectation that it is is wrong.
