### ISSUE TITLE
CreateInputDirPage win10

### ISSUE THREAD

**Issue by emcad** [jrsoftware/issrc#210]
CreateInputDirPage() has a problem in windows10 - Mapped network drives can not be browsed.  This functions has worked perfectly till win10.   ie Same install program setup works on win7 with mapped network drive browsing, but when installing the program on win10 the mapped network drive shows up in the list of drives but is locked from browsing into.

**Comment by DeeHants** [comment]
Mapped drives are not available (by default) to any elevated application.
There is an [option](https://technet.microsoft.com/en-gb/library/ee844140(v=ws.10).aspx) to make them available for same user elevation, but this won't help the situation when run from a LUA where the user changes.
Note that this is not unique to Windows 10 and was introduced in Vista.

**Comment by martijnlaan** [comment]
I've added a FAQ for this at http://jrsoftware.org/isfaq.php#missingmappeddrives
