### ISSUE TITLE
[Question/Feature Request] Check if Assembly is in GAC Already

### ISSUE THREAD

**Issue by ab-tools** [jrsoftware/issrc#211]
Is there a way to check if an assembly with a certain name is in the .NET Global Assembly Cache (GAC) already and if yes, ideally also get its version?

I need to check if a certain assembly is already installed and if not run another installer as pre-requirement for my application. Therefore I would need this check to be performed in Inno Setup.

While searching for a solution I just found this Fusion API source code in the Inno Setup source itself:
https://github.com/jrsoftware/issrc/blob/master/Projects/LibFusion.pas

Unfortunately I don't have much clue about Pascal, I can do simple things, but Fusion API interops are a bit too much for me. ;-)

But as there seems some Fusion API usage in Inno Setup source itself already, maybe there is a built in function that I missed for checking if an assembly is in the GAC already?
I think that would be very useful!

Thanks a lot in advance for any tip on that
Andreas

**Comment by martijnlaan** [comment]
Please use the newsgroup. See the guidelines which are linked when you create a new issue. https://github.com/jrsoftware/issrc/blob/master/CONTRIBUTING.md I don't know if the Fusion API supports this but you can write a C# DLL yourself and call that, as the C# example DLL shows.
