### ISSUE TITLE
Support functions for modifying ACLs

### ISSUE THREAD

**Issue by clsid2** [jrsoftware/issrc#212]
It is currently possible to modify file/dir/registry access permissions through the main script, but it would be useful to have Pascal functions for that as well.

In addition to granting "read" permissions, it would also be nice to be able to reduce to "read" access. For example to restore previous permissions after access permissions were expanded temporarily.

Functions for modifying the owner would be handy as well. Allowing to set "Administrators" and "TrustedInstaller" group as owner would be enough for my personal needs.

**Comment by martijnlaan** [comment]
Please use SetACL. http://jrsoftware.org/isfaq.php#perms
Also please use the newsgroup before posting stuff like this, see https://github.com/jrsoftware/issrc/blob/master/CONTRIBUTING.md which is linked by the New Issue screen.
