### ISSUE TITLE
predefined vars are empty (__FILE__, __PATHFILENAME__)

### ISSUE THREAD

**Issue by jakoch** [jrsoftware/issrc#214]
Hey Martijn,

i wrote the following lines to dump the content of the predefined variables and found out that 
 `__FILE__` and `__PATHFILENAME__`  are empty.

```
#emit WriteIni( '\predefined_vars.ini', 'Main', '__FILE__', __FILE__)
#emit WriteIni( '\predefined_vars.ini', 'Main', '__PATHFILENAME__', __PATHFILENAME__ )
```

Output:
```
[Main]
__FILE__=
__PATHFILENAME__=
```

Is this a bug or am i doing something wrong?

Best, Jens

**Comment by DeeHants** [comment]
Is this in the root script or a `#include`d one?
Could it be this condition mentioned in the help:
>...  Empty string for the root file.

**Comment by jakoch** [comment]
Yes, it is in the root script and the condition applies. Seems i'm doing something wrong.

How do i get access to the currently processed iss filename, when __FILE__ is empty?

**Comment by DeeHants** [comment]
I don't think that's available. The root script is passed to the compiler as a stream, not a pathname.

**Comment by jakoch** [comment]
Hmm, that makes it a bit more complicated to grab a part of the filename.
I will modify my build script and insert part of the filename into the iss as a new define before compiling.
Thank you for your quick response :+1:

**Comment by martijnlaan** [comment]
I'm glad Deanna could help you but please use the newsgroup for questions next time.
