### ISSUE TITLE
Inno setup 5.5.8 wrong path for exe file in sub-folder

### ISSUE THREAD

**Issue by L0v3craft** [jrsoftware/issrc#215]
HI I was using inno setup quickstart pack 5.5.6 and it was perfect.

I installed inno 5.5.8 quickstart pack 5.5.8 and i'm having some problem.

Ok if i start inno i can select appname, company and i can select path of the program and program exe file, so look this screen:

https://imageshack.com/a/img923/4795/pbnczw.jpg

like you can see I selected the main .exe in \Binaries\Win32\ so it is located not in main folder of the program but in a sub-folder.

Now this is the code that I have

https://imageshack.com/a/img923/4180/Z6CrAt.jpg

inno script studio automatically write the wrong exe path, it is not the main folder of the program but like i said already it is in \Binaries\Win32\ .

But why it did this ? I worked with inno quickstart pack 5.5.6 and i never seen this problem , the correct path was correct also if the exe was in some sub-folder.

**Comment by martijnlaan** [comment]
Please use the newsgroup for questions.
