### ISSUE TITLE
Remove "_is1" suffix from uninstall reg-key

### ISSUE THREAD

**Issue by gorootde** [jrsoftware/issrc#216]
See [this search result](https://github.com/jrsoftware/issrc/search?utf8=✓&q=is1&type=Code) for code lines where an "_is1" suffix is appended to the uninstall registry key.

We've switched from our old Setup provider to Innosetup. Innosetup does append this suffix, which leads to the problem that "old setups" (not based on Innosetup) do not recognise that a "new setup" (based on Innosetup) is installed. The standard procedure for such a scenario is to simply reuse the app-id of the old setup, in the new setup, and windows takes care of uninstalling the previous setup (does not matter if the same setup technology was used).

The appended  innosetup suffix hinders you from reusing the old app-id.

**Comment by DeeHants** [comment]
Windows does not "take care of uninstalling the previous setup", and it must be something added to your installer.
If you want Inno to do the same, then you'll need to detect the old key and run the uninstaller from `[Code]`.
Also there is no way to remove the `_is1` suffix.

Note that these issues should be discussed in the newsgroup first as per the notice when you created this issue.

**Comment by gorootde** [comment]
Of course there is no way, this ticket was about creating a way to do this. I've forked your code and removed the suffix, which resulted in a working uninstallation process in both directions (old setup to innosetup, and innosetup to old setup)

This suffix was already discussed in [#207](https://github.com/jrsoftware/issrc/issues/207).

But ok, it seems like feature requests are undesirable from your point of view. I'll stay with my fork.

**Comment by DeeHants** [comment]
This seems to almost exactly a duplicate of #207 then.

**Comment by gorootde** [comment]
...which was also closed a few seconds after it was opened.

**Comment by uecasm** [comment]
As was noted in the other issue, having a collision between some other installation system and an Inno-based installer causes quite a few problems, which is one of the reasons why the `_is1` suffix exists.  Try to remove it at your peril.

The correct thing to do is to have the Inno installer detect the presence of the old install and then automatically uninstall it before proceeding (or request that the user do so manually and refuse to continue until they have done so).  Discussion of how to do this should be taken to the newsgroup.
