### ISSUE TITLE
Faild to Compile Unicode Version

### ISSUE THREAD

**Issue by Motaz-Alnuweiri** [jrsoftware/issrc#217]
When I try to compile unicode version via `compile-unicode.bat` I get this error:

```
D:\>compile-unicode.bat
- ISPP.dpr
CodeGear Delphi for Win32 compiler version 20.0
Copyright (c) 1983,2008 CodeGear
ISPP.dpr(7) Fatal: F1027 Unit not found: 'System.pas' or binary equivalents (.dcu)
*** FAILED ***
```

I use Delphi 2009 to compile the code, so I remove `--no-config` for compiler command line in `compile-unicode.bat` and it's compiled successfully.

**Comment by martijnlaan** [comment]
Is there a System.dcu in your Delphi 2009 lib dir?
And what does bin\dcc32.cfg say?

**Comment by Motaz-Alnuweiri** [comment]
Yes there `System.dcu` in Delphi 2009 lib dir, and the path in `bin]dcc32.cfg` are correct look:
```
-aWinTypes=Windows;WinProcs=Windows;DbiProcs=BDE;DbiTypes=BDE;DbiErrs=BDE
-u"D:\Program Files\CodeGear\RAD Studio\6.0\lib";"D:\Program Files\CodeGear\RAD Studio\6.0\lib\Obj"
```
Before the last modified it's complied without any problems.

**Comment by martijnlaan** [comment]
There's probably something wrong with either your library path or your environment variables: I searched Google and there's many messages about this, though not with one single solution.

**Comment by Motaz-Alnuweiri** [comment]
No your wrong, All my environment variables are correct look:

```
BDS = d:\program files\codegear\rad studio\6.0
BDSCOMMONDIR = C:\Users\Public\Documents\RAD Studio\6.0
BDSPROJECTSDIR = C:\Users\Motaz\Documents\RAD Studio\Projects
BDSUSERDIR = C:\Users\Motaz\Documents\RAD Studio\6.0
```

**Comment by Motaz-Alnuweiri** [comment]
I sorry it's my mistake, I set this in `compilesettings.bat`:

```
set DELPHI2009ROOT=D:\Program Files\CodeGear\RAD Studio\6.0
set DELPHIXEROOT=D:\Program Files\CodeGear\RAD Studio\6.0
```

`DELPHIXEROOT` cause this problem, Maybe now you laugh loud at what I did :D
