### ISSUE TITLE
Pathnames > 255 Characters lead to an error

### ISSUE THREAD

**Issue by gorootde** [jrsoftware/issrc#218]
I've got innosetup running on our buildserver, which results in pretty long base paths.
It seems like there is an Issue with Pathnames > 255 Characters. Log Output is:

> Compressing: D:\FO-ToolchainData\ammbom-home\xml-data\build-dir\131073\ASDE-DEV-AN\ASDE-all\distribution.ersveicvtool\target\Distribution (PC-Tool)-1.5.7.0.0-SNAPSHOT-setup\licenses\sources\com.googlecode.concurrentlinkedhashmap.concurrentlinkedhashmap-lru-1.4.1-sources.zip
> SetupScript.iss: The System cannot find the path specified.

The file in the "Compressing:" line does exist, I've checked it multiple times. As soon as I use a base path < 255 characters, the compression step works.

**Comment by martijnlaan** [comment]
Inno Setup doesn't support such long path names, nor do many parts of Windows.

**Comment by gorootde** [comment]
Yes, that is exactly what I stated. Isn't it desirable to implement support for > 255 characters?

**Comment by retrorich75** [comment]
Limits and workarounds documented on MSDN:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

Why not map the folder at a shorter level ? command syntax use command
prompty "net use x: \\localhost\c$\Folder\Example"


On Wed, Mar 2, 2016 at 12:35 PM, gorootde <notifications@github.com> wrote:

> Yes, that is exactly what I stated. Isn't it desirable to implement
> support for > 255 characters?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrsoftware/issrc/issues/218#issuecomment-191197582>.
>



-- 
Okay what did you break today?  On second thoughts don't tell me let me
guess!

**Comment by mfriedrich74** [comment]
Just stumbled over a similar issue. As this been fixed since?
From above MSDN page: 

> The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters.

I am assuming as the case for many tools, the Unicode versions need to be used.
Does the Unicode build use such API?

**Comment by Kayli** [comment]
@martijnlaan Can you please fix the damn bug? Here is a hint:

**Comment by ajtruckle** [comment]
It doesn’t affect me personally but I did recently learn off this `\\?` Prefix. 

It might sound like a simple implementation but there may be a lot of work involved to make the changes. I don’t know.

**Comment by DeeHants** [comment]
@kayli, this is not a simple search/replace.
It requires updating the api calls used and reworking a good chunk of the file handling.
Even the post you linked to doesn't have a full solution.
The common mantra of "all patches welcome" still applies, but cursing won't help.

**Comment by ronaldhoek** [comment]
As a workaround you can start the Inno Setup compiler using a 'short' base path:

For example, in your case I expect your base path is:

`The path 'D:\FO-ToolchainData\ammbom-home\xml-data\build-dir\131073\ASDE-DEV-AN\ASDE-all\distribution.ersveicvtool\target\Distribution (PC-Tool)-1.5.7.0.0-SNAPSHOT-setup'
`
The short version of this path will be someting like:

`d:\FO-TOO~1\AMMBOM~1\xml-data\BUILD-~1\131073\ASDE-D~1\ASDE-all\DISTRI~1.ERS\target\DISTRI~1.0-S`

This is about 60 characters less...

In a batch file you ca get the short path name using:

`for /d %A in ("<yourpath>") do echo %~sA`

Or use the Windows API call to get the short path

Last, you can use still 'subst' to get a short path to the long path:

`subst x: "D:\FO-ToolchainData\ammbom-home\xml-data\build-dir\131073\ASDE-DEV-AN\ASDE-all\distribution.ersveicvtool\target\Distribution (PC-Tool)-1.5.7.0.0-SNAPSHOT-setup"`

and use `subst x: /d` to remove the 'x:' driver reference again.

**Comment by mfriedrich74** [comment]
And there come times when this isn't sufficient anymore. What then?

When is this old win 3.1 problem be resolved? I recommend dropping support for systems older than win XP and implement the proper api which supports long paths. Is porting to free pascal Lazarus helpful, maybe?

**Comment by Kayli** [comment]
@DeeHants thank you for a feedback, I was just surprised that there were no elaborate explanation about why this issue was closed. I think that stated reason was not very adequate: "Inno Setup doesn't support such long path names, nor do many parts of Windows."

But I've ended up resolving my problem with "\\?" trick, so not an issue for me at the moment.
