### ISSUE TITLE
Add VersionMajor/VersionMinor to uninstall registry

### ISSUE THREAD

**Issue by uecasm** [jrsoftware/issrc#219]
In 5.2.4, Inno started adding `MajorVersion` and `MinorVersion` values to the Uninstall registry automatically.

Per https://msdn.microsoft.com/en-us/library/windows/desktop/aa372105(v=vs.85).aspx and the App Certification Kit (from multiple reports on the newsgroup), it appears that Microsoft prefer `VersionMajor` and `VersionMinor` instead.

We should probably at least add these values.  I don't know if we should replace the old ones or not.

**Comment by DeeHants** [comment]
Personally, I'd leave them, I now have code that relies on them to detect a downgrade (or major version change, and it'd be a slight PITA to check multiple values. While new code could be fixed, any older code would fail to detect newer versions.

Oddly, (last I checked) `Major/MinorVersion` where the documented values while `VersionMajor/Minor` where only every mentioned by the certification kit.

**Comment by uecasm** [comment]
@DeeHants The Uninstall registry key structure has always been a bit of an inconsistent undocumented mess, so that doesn't surprise me.  Still, "whatever Windows Installer does" is typically the assumed standard in this regard nowadays.
