### ISSUE TITLE
ValueName is not always ignored when ValueType is none

### ISSUE THREAD

**Issue by martinprikryl** [jrsoftware/issrc#220]
[The documentation for `ValueType` prameter of `[Registry]` section entry](http://www.jrsoftware.org/ishelp/index.php?topic=registrysection&anchor=ValueType) claims that:

> If `none` (the default setting) is specified, Setup will create the key but not a value. In this case the **`ValueName`** and `ValueData` **parameters are ignored**.

This is not 100% accurate. When combined with some flags, the `ValueName` is used. For example, `deletevalue`, `uninsclearvalue`, `uninsdeletevalue`.

I think that the documentation should be updated to cover a behavior with these flag.

**Comment by DeeHants** [comment]
This is called out in the help for the `deletevalue` flag, but I agree a "where excepted below" may help.

**Comment by martinprikryl** [comment]
Thanks.
