### ISSUE TITLE
Add option to allow window portion of custom pages to be shown in Silent mode

### ISSUE THREAD

**Issue by klm1** [jrsoftware/issrc#223]
It would be really nice if Custom Pages had an optional property that when set, would allow the page window to be shown in Silent mode -- in the same way that the Install window is shown in silent mode. This could be vary handy for custom work that takes some time, but doesn't require user input.

For example, we put up an "Optimizing" page after the files are installed. This page is up while the .NET ngen tool runs. The page only has a progress bar and a bit of text (no user selectable controls). This works great in regular mode to let the user know something is going on (just as the Install page does); in Silent mode however, after the Install window is dismissed, the setup app can still run for quite a while with no indication to the user what is going on.

Would love to see this feature in this wonderful tool at some point.

**Comment by martijnlaan** [comment]
Please use the newsgroup.
