### ISSUE TITLE
OutputManifestFile no longer support path. Bug introduced in 5.5.9(u) version

### ISSUE THREAD

**Issue by Metek123** [jrsoftware/issrc#226]
The path is no longer supported at all in OutputManifestFile.

How to reproduce:
   1. Use Inno-Setup Compiler 5.5.9(u)
   2. Take any sample that comes with compiler. I took 64BitTwoArch.iss
   3. Make sure that script build Ok
   4. At end of [Setup] section add OutputManifestFile=TestMani.txt
   5. Make sure that script still build Ok
   6. Add any path. E.g. OutputManifestFile=o:\TestMani.txt
   7. Verify that compile now fails

**Comment by DeeHants** [comment]
@martijnlaan This seems to be a side effect of 3b1d7c12b1d50f67e008c3d257941cd7cfe3a6c8 where values containing `:` are rejected.
Relative paths are fine, but absolute (with drive specifiers) are rejected.

**Comment by martijnlaan** [comment]
Thanks!
