### ISSUE TITLE
FileCopy does not preserve file permissions on windows

### ISSUE THREAD

**Issue by matthewhudghton** [jrsoftware/issrc#227]
OS : Windows 7
Version: Inno Setup 5.5.3

The "Support Functions Reference" states that FileCopy copies files "...preserving time stamp and file attributes".

However I've found when running this function on files having permission:everyone-readexec; this is not the case.
The original file has everyone:read&execute permission however the copied file only has everyone:SpecialPermissions.

**Comment by martijnlaan** [comment]
Attribute means things like the hidden and read only attributes. Permissions aren't attributes.
Please use the newsgroup next time as requested by the guidelines.
