### ISSUE TITLE
Error 206 : Filename or extension is too long

### ISSUE THREAD

**Issue by manodupont** [jrsoftware/issrc#228]
How do i get rid of this  when installing a nodejs app with node_modules.

Thanks.

**Comment by manodupont** [comment]
mmm yes ?

**Comment by DeeHants** [comment]
Please see the text you deleted before typing the question:
> Before submitting your issue please first read https://github.com/jrsoftware/issrc/blob/master/CONTRIBUTING.md, also linked above. Do not submit questions here! Only submit feature requests if you have already discussed them on the newsgroups (web-based interface available, see http://www.jrsoftware.org/newsgroups.php). Thanks!
> 
> If you ignore these instructions your issue will most likely be closed without notice.

Questions should be posted to the news group (linked above).
