### ISSUE TITLE
Error with x64 files on 32 bit machine

### ISSUE THREAD

**Issue by TomB2** [jrsoftware/issrc#229]
Bug on 32 bit mahines (Win7 in that case):
Internal error: Cannot install files to 64-bit locations on this version of Windows

This causes the error:

[Files]
Source: "DB\amd64\*"; DestDir: "{app}\bin\amd64"; Flags: createallsubdirs recursesubdirs 64bit; Components: Binaries

The following one works fine. Note the missing **64bit** flag

[Files]
Source: "DB\amd64\*"; DestDir: "{app}\bin\amd64"; Flags: createallsubdirs recursesubdirs; Components: Binaries

The error message comes from Main.pas:

` if fo64Bit in FileEntry.Options then begin`
`    if not IsWin64 then`
`      InternalError('Cannot install files to 64-bit locations on this version of Windows');`
`    Result := True;`
`  end;`

**Comment by martijnlaan** [comment]
Use the newsgroup please. Include a full script when you do.

**Comment by TomB2** [comment]
Maybe a silly question: Which news group? And how to do that?
You might add it there. It is just a bug. All necessary details are already provided.

**Comment by KrystianBigaj** [comment]
IMO this is not a bug. This flag doesn't tell if you want to install this file on x64 or x86. See docs:
> **64bit**
Causes the {sys} constant to map to the 64-bit System directory when used in the Source and DestDir parameters, the regserver and regtypelib flags to treat the file as 64-bit, and the sharedfile flag to update the 64-bit SharedDLLs registry key. This is the default behavior in a 64-bit mode install.

I think that what you need is:
- Check: IsWin64  // this entry will be installed only on x64
- Check: not IsWin64 // this entry will be installed only on x86

**Comment by TomB2** [comment]
You are right. Thanks for clarification and sorry for the inconvenience..
