### ISSUE TITLE
RequireRadioSelection on TNewCheckListBox is unknown

### ISSUE THREAD

**Issue by VivienRuizFei** [jrsoftware/issrc#234]
I've noticed that we cannot access TNewCheckListBox.RequireRadioSelection, whereas it is documented (http://stackoverflow.com/questions/40682621/innosetup-why-requireradioselection-is-unknown-on-a-tinputoptionwizardpage)

This subject has been raised in this newsletter by Martin Prikryl: http://news.jrsoftware.org/news/innosetup/msg102964.html

He's pointing out that the property is not declared in RegisterNewCheckListBox_C.

**Comment by martijnlaan** [comment]
Thanks 👍
