### ISSUE TITLE
Translation error - Portuguese Brazil

### ISSUE THREAD

**Issue by LucasKrahl23** [jrsoftware/issrc#235]
We found a translation error when we used the language Portuguese Brazil.
In this message EntryAbortRetryIgnore has an 'OR', but the correct one is 'or'.

Wrong: 
EntryAbortRetryIgnore=Clique Repetir para tentar novamente, Ignorar para continuar assim mesmo, or Cancelar para cancelar a instalação.

Right:
EntryAbortRetryIgnore=Clique Repetir para tentar novamente, Ignorar para continuar assim mesmo, ou Cancelar para cancelar a instalação.

**Comment by martijnlaan** [comment]
I think you mean the correct one is 'ou' not 'or'? 

But thanks, please contact the maintainer of the translation so it can be fixed.
