### ISSUE TITLE
Uninstaller Leaving Compatibility Assistant\Store Registry setting in Windows 8 & 10

### ISSUE THREAD

**Issue by MartinSedgewick** [jrsoftware/issrc#238]
When installing and then immediately uninstalling, there is a registry setting which is created and not deleted. Therefore, it is created when the installer is run, by Windows I believe.

HKCU\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store

I have found this is applicable on Windows 8 and 10. It is not applicable on Windows 7. (all 64-bit OS)

I am installing 32-bit executables, and I believe the compatibility assistant is possibly being triggered due to this.

Is it possible to have the installer automatically delete these registry settings on uninstall?

**Comment by DeeHants** [comment]
That key and values inside it are not created by Inno Setup, therefore should not be deleted by Inno Setup.
It's an implementation details of the Windows Program Compatibility Assistant:
http://journeyintoir.blogspot.co.uk/2013/12/revealing-program-compatibility.html

**Comment by MartinSedgewick** [comment]
Thanks for the information Deanna.
