### ISSUE TITLE
[Feature] Unicode string literals

### ISSUE THREAD

**Issue by ElSanchez666** [jrsoftware/issrc#240]
Inno Setup help says:
> The new RemObjects PascalScript version used by the Unicode compiler supports Unicode, but not for its input source. This means it does use Unicode string types as said, but any literal Unicode characters in the script will be converted to ANSI. This doesn't mean you can't display Unicode strings: you can for example instead use encoded Unicode characters to build Unicode strings (like S := #$0100 + #$0101 + 'Aa';), or load the string from a file using LoadStringsFromFile, or use a {cm:...} constant.

To work around this, change `TScriptCompiler.Compile` implementation in `ScriptCompiler.pas`:
``` Pascal
function TScriptCompiler.Compile(const ScriptText: String; var CompiledScriptText, CompiledScriptDebugInfo: tbtString): Boolean;
...
  { Note: Cast disabled on non-Unicode to work around D2 codegen bug }
  FScriptText := {$IFDEF UNICODE}UTF8Encode{$ENDIF}(ScriptText);
...
PSPascalCompiler.UTF8Decode := True;

**Comment by martijnlaan** [comment]
Thanks, I didn't know about such an option. Did you test it yourself?

**Comment by ElSanchez666** [comment]
>Did you test it yourself?

This simple test is ok.
``` Pascal
[Setup]
AppName=test
AppVerName=test
OutputDir=.
DefaultDirName={tmp}
DirExistsWarning=no
Uninstallable=no
CreateUninstallRegKey=no

[Code]
const
  Ccc = '道';

procedure InitializeWizard;
begin
  MsgBox(IntToStr(Length(Ccc +
    'dfdf' +
    'ーム' +
    'ジ'
   )), mbError, MB_OK);
  MsgBox(Ccc + '公式ホームページ', mbError, MB_OK);
end;

**Comment by ElSanchez666** [comment]
@martijnlaan, I'm sorry I misled you. I have some changed ROPS source code when post my previous comment. You must fix bug in procedure `CopyVariantContents` in `uPSCompiler.pas` too:
```Pascal
// btwidechar: Dest^.tchar := src^.tchar;
btwidechar: Dest^.twidechar := src^.twidechar;

**Comment by martijnlaan** [comment]
Thanks. Updated in next version.
