### ISSUE TITLE
Chr( ) function cannot handle unicode

### ISSUE THREAD

**Issue by cuixiping** [jrsoftware/issrc#242]
Inno Setup 5.5.9 unicode version.

Ord( ) can accept a double bytes char,  but Chr( ) cannot accept the code of a double bytes char.
So I cannot convert code 20013 (0x4E2D) to the east asia char '中'.

var s: String;
s := '中';
Log( IntToStr(Ord(s[1])) ); //20013
Log(Chr(20013));  //an unreadable char

**Comment by cuixiping** [comment]
In other words, there is a bug of Chr( ) in inno unicode version

**Comment by martijnlaan** [comment]
You could try posting an issue at https://github.com/remobjects/pascalscript. This shouldn't include the above example though because your `s := '中';` line is unsupported, see http://jrsoftware.org/ishelp/topic_unicode.htm.

**Comment by cuixiping** [comment]
I posted an issue at pascalscript: https://github.com/remobjects/pascalscript/issues/156
