### ISSUE TITLE
uninsneveruninstall flag does not work in Dirs section

### ISSUE THREAD

**Issue by dinprojector** [jrsoftware/issrc#243]
Consider the following snippet:

```
[Dirs]
Name: "{app}\example"; Flags: uninsneveruninstall
```

The installer will create correctly the folder named as example in app dir, 
but the uninstaller will continue to remove example folder, even if the flag uninsneveruninstall is enabled.
I have the same behaviour also if example folder is not empty.

Affected version [5.5.9].

**Comment by dinprojector** [comment]
More information about closing this issue?

**Comment by KngStr** [comment]
@dinprojector  When you post new issue, you will get this:

Only submit an issue if you have already discussed it on the newsgroups first (web-based interface available, see http://www.jrsoftware.org/newsgroups.php). Thanks!

If you ignore these instructions your issue will be closed without notice and your username will be **blocked** from submitting any new issues.
