### ISSUE TITLE
Innosetup seems dead because of no updates

### ISSUE THREAD

**Issue by patlecat** [jrsoftware/issrc#248]
You know what I mean. No updates, no maintenance, no fixes, no new features means it is dead. No one is working on its development anymore. I just would like to know why? Newsgroups are fine for lengthy discussions and chatter. I just want to know if a new version is planned anytime soon or not? Please give a straight answer.

**Comment by ajtruckle** [comment]
I guess "If it ain't broken why fix it". I have been hoping for some of the third party translations to be revamped. I am intersted in this issue.

Also, I really don't see the need to stamp down on a user raising an issue via this resource. I have often used Stackoverflow now for my InnoSetup issues and have had some excellent user support.

Maybe a semi-annual newsletter wouldn't hurt to the user base.

**Comment by patlecat** [comment]
Yeah like there's 1 software out there that has no bugs and no need to adapt to new technology like OS and libs getting refreshed almost monthly  ;-)

**Comment by dmitry-pavlov** [comment]
The most recent update I have got was about Inno Setup 5.5.7 release on January 3, 2016.

**Comment by ajtruckle** [comment]
@dmitry-pavlov According to here:

http://www.jrsoftware.org/

April 6, 2016 - Inno Setup 5.5.9 released.

**Comment by DeeHants** [comment]
There have been no significant Windows updates that require changes in Inno Setup.
As for development, the team behind it is tiny (1 person primarily).
If there is any specific feature you're looking for, then we're more than happy for it to be discussed on the news groups, or for people to write the code and submit it (this is how `[code]` appeared, as well as numerous other key features.

As for "is this project alive", this isn't really the place to discuss them unless you have a specific well defined problem.

**Comment by mfriedrich74** [comment]
I love to see:
* long file path support utilizing Windows Unicode file API
* support for external optional components, which have their files saved in a data file

**Comment by ronaldhoek** [comment]
> support for external optional components, which have their files saved in a data file
Inno Setup has pascal scripting support, which allows loading of dll modules

**Comment by martijnlaan** [comment]
This is not the place for feature requests, please use the newsgroups.
