### ISSUE TITLE
Copyright "©" and Registered "®" was not display correctly in License Page

### ISSUE THREAD

**Issue by dennislwy** [jrsoftware/issrc#249]
I noticed InnoSetup License page was not display my contents correctly whenever LicenseFile contains character symbol of © (copyright) or ® (registered).

I tried using both normal and unicode version of InnoSetup 5.5.9.

Below is the sample content of my LicenseFile and what was displayed in the installer made by InnoSetup.  

![capture](https://user-images.githubusercontent.com/5407099/34592433-e758ce94-f1fe-11e7-9582-f850aacf2f01.JPG)  

![capture2](https://user-images.githubusercontent.com/5407099/34592434-e78d3d28-f1fe-11e7-8cdd-c205e7d74757.JPG)

**Comment by dudul** [comment]
Open the file in windows notepad and save it as Unicode.


![2018-01-05_094852](https://user-images.githubusercontent.com/4558838/34599931-b009d6b4-f1fd-11e7-9e47-6d70bc1b52e7.png)

**Comment by ronaldhoek** [comment]
But when you (also) use the non-unicode versin of Inno Setup, this will not work.

**Comment by DeeHants** [comment]
How're you loading the file contents into the control?
That will have an impact on how it's interpreted.
Note that if you're seeing the Å character then the file is NOT ANSI, it's UTF-8.

Also note that these issues are for verified Inno bugs. For support, you should really post to the newsgroups.

**Comment by dennislwy** [comment]
@ronaldhoek i tried, it works! thanks
@DeeHants i was previously saving it with Sublime, maybe it was saving it in UTF-8

**Comment by martijnlaan** [comment]
This is not the place for support requests, please use the newsgroups next time. http://news.jrsoftware.org/read/
